using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Reflection;
using System.Runtime.InteropServices;
using LuoTianyiPet.Core;
using LuoTianyiPet.Platform.Windows;
using Button=System.Windows.Controls.Button;
using CheckBox=System.Windows.Controls.CheckBox;
using TextBox=System.Windows.Controls.TextBox;
namespace LuoTianyiPet.App;
public partial class MainWindow
{
    [DllImport("user32.dll",EntryPoint="GetForegroundWindow")]private static extern nint PlannerQaForeground();
    private async Task RunPlannerQaAsync()
    {
        string path=Path.Combine(AppContext.BaseDirectory,"PlannerQa",DateTime.UtcNow.Ticks.ToString());Directory.CreateDirectory(path);List<string> checks=[];
        try
        {
            using ReminderService service=new(new LocalAppPaths(Path.Combine(path,"UserData")));await service.LoadAsync();
            DateTime day=DateTime.Today.AddDays((8-(int)DateTime.Today.DayOfWeek)%7);
            await service.ChangeAsync(b=>{for(int n=0;n<3;n++)b.Items.Add(new ReminderItem{Calendar=true,Title=new[]{"周会","项目讨论","运动"}[n],Notes=new[]{"核对本周计划","准备演示资料，确认下一阶段安排","跑步5公里"}[n],Start=day.AddHours(9+n*4),Enabled=n<2,ReminderCreated=n<2,EarlyEnabled=false});b.Items.Add(new ReminderItem{Title="起床",Start=day.AddHours(8.5),Repeat=ReminderRepeat.Daily,ReminderCreated=true,EarlyEnabled=false});b.Items.Add(new ReminderItem{Title="喝水休息一下",Relative=true,Start=DateTime.Now.AddMinutes(30),DurationSeconds=1800,ReminderCreated=true,EarlyEnabled=false});});
            PlannerWindow window=new(service,false);window.Show();await Task.Delay(150);
            void Check(bool condition,string name){if(!condition)throw new InvalidOperationException(name);checks.Add("PASS "+name);}
            IEnumerable<DependencyObject> Tree(DependencyObject d){yield return d;for(int n=0;n<VisualTreeHelper.GetChildrenCount(d);n++)foreach(var x in Tree(VisualTreeHelper.GetChild(d,n)))yield return x;}
            FrameworkElement Named(Window w,string name)=>Tree(w).OfType<FrameworkElement>().FirstOrDefault(x=>x.Name==name)??throw new InvalidOperationException($"missing named element: {name}");
            void Click(Window w,string name)=>((Button)Named(w,name)).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));
            void Snapshot(Window w,string name,bool dpi=false){w.UpdateLayout();void Shot(string file,double scale){var bmp=new RenderTargetBitmap((int)Math.Ceiling(w.ActualWidth*scale),(int)Math.Ceiling(w.ActualHeight*scale),96*scale,96*scale,PixelFormats.Pbgra32);bmp.Render(w);PngBitmapEncoder png=new();png.Frames.Add(BitmapFrame.Create(bmp));using var f=File.Create(Path.Combine(path,file+".png"));png.Save(f);}Shot(name,1.0);if(dpi){Shot(name+"-125",1.25);Shot(name+"-150",1.5);}checks.Add("PASS rendered "+name+(dpi?" @100/125/150":""));}
            void Set(string name,object value)=>typeof(PlannerWindow).GetField(name,BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(window,value);
            void CaptureAttachment()
            {
                var card=_reminderCard!;var bounds=new Rect(Left,Top,ActualWidth,ActualHeight);bounds.Union(new Rect(card.Left,card.Top,card.ActualWidth,card.ActualHeight));bounds.Inflate(16,16);
                DrawingVisual visual=new();using(var dc=visual.RenderOpen()){dc.DrawRectangle(new SolidColorBrush(Color.FromRgb(234,245,255)),null,new Rect(0,0,bounds.Width,bounds.Height));dc.DrawRectangle(new VisualBrush(this),null,new Rect(Left-bounds.Left,Top-bounds.Top,ActualWidth,ActualHeight));dc.DrawRectangle(new VisualBrush(card),null,new Rect(card.Left-bounds.Left,card.Top-bounds.Top,card.ActualWidth,card.ActualHeight));}
                var bmp=new RenderTargetBitmap((int)Math.Ceiling(bounds.Width),(int)Math.Ceiling(bounds.Height),96,96,PixelFormats.Pbgra32);bmp.Render(visual);PngBitmapEncoder png=new();png.Frames.Add(BitmapFrame.Create(bmp));using var file=File.Create(Path.Combine(path,"20-pet-attached.png"));png.Save(file);checks.Add("PASS rendered pet and attached card in their actual relative positions");
            }
            var precedenceBook=new ReminderBook{RestWeekdays=[DayOfWeek.Friday]};DateTime precedenceDay=new(2026,9,18);ReminderSchedule.SetRestOverride(precedenceBook,precedenceDay,false,DateTime.Now);Check(!precedenceBook.IsRest(precedenceDay),"A31 date override takes priority over weekly rest");ReminderSchedule.SetRestOverride(precedenceBook,precedenceDay,null,DateTime.Now);Check(precedenceBook.IsRest(precedenceDay),"A31 restore default follows weekly rest");
            var editMethods=typeof(PlannerWindow).GetMethods(BindingFlags.NonPublic|BindingFlags.Instance).Where(m=>m.Name=="Edit").ToList();
            void Edit(ReminderItem? i,bool calendar){editMethods.Single(m=>m.GetParameters().Length==2).Invoke(window,new object?[]{i,calendar});window.UpdateLayout();}
            Set("_date",day);window.Navigate(false);Snapshot(window,"01-month",true);
            var setWorkdaysButton=(Button)Named(window,"SetWorkdays");var workdayNav=(StackPanel)VisualTreeHelper.GetParent(setWorkdaysButton);var todayButton=workdayNav.Children.OfType<Button>().First(b=>Equals(b.Content,"今天"));Check(Equals(setWorkdaysButton.Content,"设置班休")&&workdayNav.Children.IndexOf(setWorkdaysButton)==workdayNav.Children.IndexOf(todayButton)+1&&Equals(setWorkdaysButton.Background,PlannerTheme.Soft)&&Equals(todayButton.Background,PlannerTheme.Soft)&&!Tree(window).OfType<Button>().Any(b=>Equals(b.ToolTip,"设置工作/休息日")),"A43 settings entry is the pale blue labeled button directly after Today instead of a header gear");
            Check(((Button)Named(window,"PreviousMonth")).Style==window.FindResource("PlannerIconBtn")&&((Button)Named(window,"NextMonth")).Style==window.FindResource("PlannerIconBtn"),"A40 month navigation uses two plain chevrons around the clickable year and month");
            Click(window,"PreviousMonth");window.UpdateLayout();Check(((DateTime)typeof(PlannerWindow).GetField("_date",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!).Month==8,"A40 left chevron moves to the previous month");Click(window,"NextMonth");window.UpdateLayout();
            Click(window,"MonthJump");await Task.Delay(60);window.UpdateLayout();var monthPopup=(System.Windows.Controls.Primitives.Popup)Named(window,"MonthPickerPopup");if(!monthPopup.IsOpen){Click(window,"MonthJump");await Task.Delay(60);window.UpdateLayout();monthPopup=(System.Windows.Controls.Primitives.Popup)Named(window,"MonthPickerPopup");}Check(monthPopup.IsOpen,"A41 clicking the year and month expands the quick month picker");
            FrameworkElement PopupNamed(string name)=>Tree(monthPopup.Child).OfType<FrameworkElement>().FirstOrDefault(x=>x.Name==name)??throw new InvalidOperationException("missing month picker element: "+name);
            var popupSurface=(FrameworkElement)monthPopup.Child;popupSurface.UpdateLayout();var pickerBitmap=new RenderTargetBitmap((int)Math.Ceiling(popupSurface.ActualWidth),(int)Math.Ceiling(popupSurface.ActualHeight),96,96,PixelFormats.Pbgra32);pickerBitmap.Render(popupSurface);PngBitmapEncoder pickerPng=new();pickerPng.Frames.Add(BitmapFrame.Create(pickerBitmap));using(var pickerFile=File.Create(Path.Combine(path,"01-month-picker.png")))pickerPng.Save(pickerFile);checks.Add("PASS rendered 01-month-picker");
            var pickerYear=(TextBox)PopupNamed("MonthPickerYear");pickerYear.Text="9999";((Button)PopupNamed("PickMonth10")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(monthPopup.IsOpen&&((DateTime)typeof(PlannerWindow).GetField("_date",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!).Year==2026,"A41 invalid year does not navigate or close the picker");pickerYear.Text="2027";((Button)PopupNamed("PickMonth10")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(!monthPopup.IsOpen&&((DateTime)typeof(PlannerWindow).GetField("_date",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!) is DateTime jumped&&jumped.Year==2027&&jumped.Month==10&&jumped.Day==day.Day,"A41 picker changes year and month while preserving the selected day");
            window.UpdateLayout();Click(window,"MonthJump");await Task.Delay(60);monthPopup=(System.Windows.Controls.Primitives.Popup)Named(window,"MonthPickerPopup");((TextBox)Tree(monthPopup.Child).OfType<FrameworkElement>().First(x=>x.Name=="MonthPickerYear")).Text="2026";((Button)Tree(monthPopup.Child).OfType<FrameworkElement>().First(x=>x.Name=="PickMonth09")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));window.UpdateLayout();
            Set("_date",new DateTime(2027,1,31));typeof(PlannerWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(window,null);window.UpdateLayout();Click(window,"MonthJump");await Task.Delay(60);monthPopup=(System.Windows.Controls.Primitives.Popup)Named(window,"MonthPickerPopup");((Button)Tree(monthPopup.Child).OfType<FrameworkElement>().First(x=>x.Name=="PickMonth02")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(((DateTime)typeof(PlannerWindow).GetField("_date",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!)==new DateTime(2027,2,28),"A41 jumping from the 31st to a shorter month selects its last day");Set("_date",day);typeof(PlannerWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(window,null);window.UpdateLayout();
            var plannerTitle=(Grid)Named(window,"PlannerTitleBar");
            var plannerChrome=System.Windows.Shell.WindowChrome.GetWindowChrome(window);
            Check(window.Width>0&&window.Height>0&&window.Width<=SystemParameters.WorkArea.Width&&window.Height<=SystemParameters.WorkArea.Height&&window.ResizeMode==ResizeMode.NoResize&&plannerChrome?.ResizeBorderThickness==new Thickness(0),"Planner fits the available desktop with no resize grip");
            var titleActions=(StackPanel)plannerTitle.Children.OfType<StackPanel>().Single(p=>Grid.GetColumn(p)==2);
            Check(titleActions.Children.Count==1&&titleActions.Children[0] is Button onlyClose&&onlyClose.Name=="PlannerCloseWindow"&&!Tree(plannerTitle).OfType<Button>().Any(b=>Equals(b.ToolTip,"最小化")||Equals(b.ToolTip,"最大化")),"Planner title bar exposes only Close");
            bool BlankTitleHit(double fraction)
            {
                var hit=VisualTreeHelper.HitTest(plannerTitle,new Point(plannerTitle.ActualWidth*fraction,plannerTitle.ActualHeight/2))?.VisualHit;
                for(DependencyObject? current=hit;current!=null&&current!=plannerTitle;current=VisualTreeHelper.GetParent(current))
                    if(current is Button)return false;
                return hit!=null;
            }
            Check(plannerTitle.Background==Brushes.Transparent&&BlankTitleHit(.33)&&BlankTitleHit(.74),"title bar blank areas receive drag input without covering navigation or window buttons");
            Check(!Tree(window).OfType<FrameworkElement>().Any(e=>e.Name=="PlannerSettingsButton"),"Planner header does not expose the removed reminder settings entry");
            Check(((Button)Named(window,"PlannerCalendarNavigation")).Content is Grid selectedTab&&selectedTab.Children.OfType<Border>().Count()==1&&((Button)Named(window,"PlannerAlarmNavigation")).Content is Grid inactiveTab&&!inactiveTab.Children.OfType<Border>().Any(),"Planner tabs show an underline only on the selected tab");
            Check(Tree(window).OfType<Button>().Any(b=>b.Name=="ManageSchedules"&&Equals(b.Content,"管理日程")),"calendar exposes schedule management next to creation");
            var body=(ScrollViewer)typeof(PlannerWindow).GetField("_body",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!;
            Check(((Grid)body.Content).ColumnDefinitions.Count==1,"A02 opening month starts with the full width calendar and no day details");
            var initialMonthCells=(Dictionary<DateTime,Border>)typeof(PlannerWindow).GetField("_calendarDateBorders",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!;
            Check(Equals(initialMonthCells[new DateTime(2026,9,14)].Background,Brushes.White)&&Equals(initialMonthCells[new DateTime(2026,9,19)].Background,PlannerTheme.RestBackground),"A36 weekly workdays are white and weekly rest days use the light pink background");
            Border? MonthBadge(DateTime date)=>Tree(window).OfType<Border>().FirstOrDefault(b=>b.Name=="OverrideBadge"+date.ToString("yyyyMMdd"));
            Check(MonthBadge(new DateTime(2026,9,14))==null&&MonthBadge(new DateTime(2026,9,19))==null,"weekly work and rest dates have no explicit badge");
            var nationalStack=(StackPanel)((Button)Named(window,"Day20261001")).Content;var nationalTexts=nationalStack.Children.OfType<TextBlock>().ToList();Check(nationalTexts.Count==2&&nationalTexts[1].Text=="国庆节","A34 festival replaces the lunar line in month cells");
            var dayStack=(StackPanel)((Button)Named(window,"Day"+day.ToString("yyyyMMdd"))).Content;Check(dayStack.Children.OfType<StackPanel>().Any(sp=>sp.Children.OfType<System.Windows.Shapes.Ellipse>().Count()==2)&&Tree(dayStack).OfType<TextBlock>().Any(t=>t.Name.StartsWith("MonthPreview")),"month shows first preview and dots for two additional items");
            Click(window,"Day"+day.ToString("yyyyMMdd"));window.UpdateLayout();Check(((Grid)body.Content).ColumnDefinitions.Count==2,"A02 clicking a day expands its details");
            var detailCards=Tree(window).OfType<Button>().Where(b=>Equals(b.ToolTip,"点击编辑日程")).ToList();Check(detailCards.Count>0&&detailCards.All(b=>b.Content is StackPanel sp&&!Tree(sp).OfType<Button>().Any()),"A42 month day-detail cards also have no colored leading strip");
            var selectedMonthCell=((Dictionary<DateTime,Border>)typeof(PlannerWindow).GetField("_calendarDateBorders",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!)[day];Check(Equals(selectedMonthCell.BorderBrush,PlannerTheme.CalendarSelection)&&Equals(selectedMonthCell.Background,PlannerTheme.CalendarBatchSelectionSoft),"selected ordinary workday uses a warm cell and distinct amber outline");
            Check(Tree(window).OfType<TextBlock>().Any(t=>t.Text.StartsWith(CalendarLabels.FullLunar(day).Replace("农历",String.Empty))&&t.Text.Contains("3项安排")),"A32 day details show the full lunar date");Snapshot(window,"01-month-details");
            Click(window,"Day"+day.ToString("yyyyMMdd"));window.UpdateLayout();Check(((Grid)body.Content).ColumnDefinitions.Count==1,"A02 same date collapses panel");
            DateTime overrideDay=day.AddDays(2);Click(window,"SetWorkdays");window.UpdateLayout();Snapshot(window,"02-workdays-clean");await service.ChangeAsync(b=>b.RestWeekdays=[overrideDay.DayOfWeek]);window.UpdateLayout();Check((bool)typeof(PlannerWindow).GetField("_batch",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!,"A31 enters rest adjustment mode");
            Check(!Tree(window).OfType<Button>().Any(b=>b.Name=="SetWorkdays")&&Tree(window).OfType<Button>().Any(b=>b.Name=="WorkdaysDoneTop"),"A43 edit mode replaces Settings Rest with Complete Rest in the same navigation area");
            Check(!Tree(window).OfType<Button>().Any(b=>Equals(b.Content,"添加日期")),"A30 rest panel uses the main calendar without a duplicate date picker");
            Check(Tree(window).OfType<Button>().Any(b=>Equals(b.Content,"恢复每周安排"))&&!Tree(window).OfType<Button>().Any(b=>Equals(b.Content,"清除指定设置"))&&!Tree(window).OfType<Button>().Any(b=>Equals(b.Content,"恢复默认")),"A32 rest panel names date reset as restoring the weekly schedule");
            Check(Tree(window).OfType<TextBlock>().Any(t=>t.Text.Contains("粉底为休息日")&&t.Text.Contains("单独设置")),"A32 rest panel explains badge source by color");
            Check(Tree(window).OfType<Button>().Any(b=>b.Name=="WorkdaysClose"),"A31 rest adjustment has one completion action");
            Check(MonthBadge(overrideDay)==null,"weekly rest has no override badge in adjustment mode");
            Check(!((Button)Named(window,"ClearSelectedDates")).IsEnabled&&!((Button)Named(window,"SetSelectedRestDays")).IsEnabled&&!((Button)Named(window,"SetSelectedWorkdays")).IsEnabled&&!((Button)Named(window,"ResetSelectedRestDays")).IsEnabled,"A30 empty rest selection disables batch actions");
            Click(window,"Day"+overrideDay.ToString("yyyyMMdd"));window.UpdateLayout();Check((bool)typeof(PlannerWindow).GetField("_batch",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!,"A31 remains in rest adjustment mode after selecting a date");Click(window,"SetSelectedWorkdays");await Task.Delay(200);Check(service.Book.RestOverrides.ContainsKey(overrideDay.ToString("yyyy-MM-dd"))&&!service.Book.IsRest(overrideDay),"A31 UI applies a date workday override over weekly rest");var explicitDateButton=(Button)Named(window,"Day"+overrideDay.ToString("yyyyMMdd"));var explicitBadge=MonthBadge(overrideDay)!;Check(Equals(explicitBadge.Background,PlannerTheme.AccentSoft)&&Equals(((TextBlock)explicitBadge.Child).Foreground,PlannerTheme.WorkForeground),"A32 explicit workday uses a blue badge without labeling ordinary workdays");Check(Equals(((Dictionary<DateTime,Border>)typeof(PlannerWindow).GetField("_calendarDateBorders",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!)[overrideDay].Background,Brushes.White),"explicit workday keeps white background");Click(window,"Day"+overrideDay.ToString("yyyyMMdd"));window.UpdateLayout();Snapshot(window,"02-workdays-explicit");Check(Tree(window).OfType<FrameworkElement>().Any(e=>e is Border&&e.ToolTip is string tip&&tip.Contains("单独设置：工作日")),"A33 selected date chips expose the explicit override status");Check((bool)typeof(PlannerWindow).GetField("_batch",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!,"A31 stays in rest adjustment mode after applying a rule");Click(window,"ResetSelectedRestDays");await Task.Delay(200);Check(!service.Book.RestOverrides.ContainsKey(overrideDay.ToString("yyyy-MM-dd"))&&service.Book.IsRest(overrideDay),"A31 UI clears the date override and follows weekly rest");
            var clearedDateButton=(Button)Named(window,"Day"+overrideDay.ToString("yyyyMMdd"));Check(((string?)clearedDateButton.ToolTip)?.Contains("跟随每周规则：休息日")==true,"A32 cleared date explains its effective weekly status");var clearedBorders=(Dictionary<DateTime,Border>)typeof(PlannerWindow).GetField("_calendarDateBorders",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!;Check(Equals(clearedBorders[overrideDay].Background,PlannerTheme.RestBackground),"A32 cleared date keeps a light effective rest background");Check(((TextBlock)typeof(PlannerWindow).GetField("_status",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!).Text.Contains("已恢复每周安排"),"A32 cleared date status explains the weekly fallback");
            DateTime explicitRestDay=new(2026,9,14);await service.ChangeAsync(b=>ReminderSchedule.SetRestOverride(b,explicitRestDay,true,DateTime.Now));window.UpdateLayout();Check(MonthBadge(explicitRestDay) is Border explicitRestBadge&&Equals(explicitRestBadge.Background,PlannerTheme.DangerSoft)&&Equals(((TextBlock)explicitRestBadge.Child).Foreground,PlannerTheme.RestForeground),"A37 explicit rest day shows a stronger rest badge on the pale rest cell");await service.ChangeAsync(b=>ReminderSchedule.SetRestOverride(b,explicitRestDay,null,DateTime.Now));window.UpdateLayout();
            var restSelection=(HashSet<DateTime>)typeof(PlannerWindow).GetField("_selected",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!;
            foreach(int n in Enumerable.Range(0,27))restSelection.Add(new DateTime(2026,8,31).AddDays(n));typeof(PlannerWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(window,null);window.UpdateLayout();var workdaysScroll=(ScrollViewer)Named(window,"WorkdaysSelectedScroll");Check(restSelection.Count==27&&workdaysScroll.ScrollableHeight>0&&((Button)Named(window,"SetSelectedRestDays")).IsVisible,"A62 twenty-seven selected workdays keep an internally scrolling list and fixed actions");Snapshot(window,"02-workdays-many",true);restSelection.Clear();typeof(PlannerWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(window,null);window.UpdateLayout();
            Click(window,"Day"+day.ToString("yyyyMMdd"));window.UpdateLayout();Check(restSelection.Count==1&&restSelection.Contains(day),"A30 single click selects one date");Click(window,"Day"+day.ToString("yyyyMMdd"));window.UpdateLayout();Check(restSelection.Count==0,"A30 single click toggles one date off");
            var dragStartButton=(Button)Named(window,"Day"+day.ToString("yyyyMMdd"));var dragEndButton=(Button)Named(window,"Day"+day.AddDays(2).ToString("yyyyMMdd"));var cellPanel=(Grid)VisualTreeHelper.GetParent(dragStartButton)!;var dayBorder=(Border)VisualTreeHelper.GetParent(cellPanel)!;var calendarGrid=(Grid)VisualTreeHelper.GetParent(dayBorder)!;
            Point dragFrom=dragStartButton.TransformToAncestor(calendarGrid).Transform(new Point(dragStartButton.ActualWidth/2,dragStartButton.ActualHeight/2));Point dragTo=dragEndButton.TransformToAncestor(calendarGrid).Transform(new Point(dragEndButton.ActualWidth/2,dragEndButton.ActualHeight/2));
            Rect startBounds=dayBorder.TransformToAncestor(calendarGrid).TransformBounds(new Rect(0,0,dayBorder.ActualWidth,dayBorder.ActualHeight));object[] boundaryArgs={calendarGrid,new Point(startBounds.Right,startBounds.Top+startBounds.Height/2),default(DateTime)};bool boundaryHit=(bool)typeof(PlannerWindow).GetMethod("TryGetCalendarDate",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(window,boundaryArgs)!;Check(boundaryHit,"A31 calendar boundary resolves to a nearby date");
            var calendarDragLastDayField=typeof(PlannerWindow).GetField("_calendarDragLastDay",BindingFlags.NonPublic|BindingFlags.Instance)!;typeof(PlannerWindow).GetField("_calendarDragStartDay",BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(window,day);calendarDragLastDayField.SetValue(window,null);typeof(PlannerWindow).GetMethod("AddCalendarDragPath",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(window,new object[]{calendarGrid,dragFrom,dragTo});
            Check(restSelection.Count==3&&Enumerable.Range(0,3).All(n=>restSelection.Contains(day.AddDays(n))),$"A30 drag selection includes every date along the path (count={restSelection.Count})");
            Point reverseFrom=dragTo,reverseTo=dragFrom;typeof(PlannerWindow).GetField("_calendarDragStartDay",BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(window,day.AddDays(2));calendarDragLastDayField.SetValue(window,null);typeof(PlannerWindow).GetMethod("AddCalendarDragPath",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(window,new object[]{calendarGrid,reverseFrom,reverseTo});
            Check(restSelection.Count==0,"A30 reverse drag over the same path cancels every date again");restSelection.Clear();restSelection.Add(day.AddDays(1));restSelection.Add(day.AddDays(2));calendarDragLastDayField.SetValue(window,null);typeof(PlannerWindow).GetField("_calendarDragStartDay",BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(window,day);typeof(PlannerWindow).GetMethod("AddCalendarDragPath",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(window,new object[]{calendarGrid,dragFrom,dragTo});
            Check(restSelection.Count==1&&restSelection.Contains(day)&&!restSelection.Contains(day.AddDays(1))&&!restSelection.Contains(day.AddDays(2)),"A30 one drag toggles mixed selected and unselected dates");Snapshot(window,"02-workdays-mixed");await service.ChangeAsync(b=>b.RestWeekdays=[DayOfWeek.Saturday,DayOfWeek.Sunday]);restSelection.Clear();typeof(PlannerWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(window,null);window.UpdateLayout();
            restSelection.Add(day);for(int n=1;n<22;n++)restSelection.Add(day.AddDays(n));typeof(PlannerWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(window,null);window.UpdateLayout();Snapshot(window,"02-workdays-selected",true);
            Check(((Button)Named(window,"ClearSelectedDates")).IsEnabled&&((Button)Named(window,"SetSelectedRestDays")).IsEnabled,"A30 selected rest dates enable clear and batch actions");
            Click(window,"SetSelectedWorkdays");await Task.Delay(200);window.UpdateLayout();
            Check(restSelection.Count==0&&Tree(window).OfType<FrameworkElement>().Any(e=>e.Name=="WorkdaysClose")&&Tree(window).OfType<FrameworkElement>().Any(e=>e.Name=="ClearSelectedDates"),"A30 applying a rest rule clears selection and stays in adjust mode");
            Click(window,"Day"+day.ToString("yyyyMMdd"));window.UpdateLayout();Check(restSelection.Count==1,"A30 adjust mode still selects dates after applying a rule");Click(window,"ClearSelectedDates");window.UpdateLayout();Check(restSelection.Count==0,"A30 clear selection removes all selected dates");
            Snapshot(window,"02-workdays",true);Click(window,"WorkdaysClose");
            await service.ChangeAsync(b=>b.WeekView=true);Snapshot(window,"03-week",true);Check(Tree(window).OfType<TextBlock>().Count(t=>t.Text=="暂无日程")>=4,"A35 empty week columns show the centered no-schedules state");
            Check(Tree(window).OfType<Button>().Where(b=>Equals(b.ToolTip,"点击编辑日程")).All(b=>b.Content is StackPanel),"A42 week cards have no colored leading strip");
            Set("_date",DateTime.Today);typeof(PlannerWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(window,null);window.UpdateLayout();
            var todayDateButton=(Button)Named(window,"Day"+DateTime.Today.ToString("yyyyMMdd"));var todayWeekHead=(StackPanel)todayDateButton.Content;Check(todayWeekHead.Children.OfType<TextBlock>().Take(2).All(t=>Equals(t.Foreground,PlannerTheme.Accent)),"today labels have independent blue emphasis");Set("_date",day);
            var qaOverrides=service.Book.RestOverrides.ToDictionary(p=>p.Key,p=>p.Value);
            var qaEvents=new List<Guid>();DateTime qaMonday=day.AddDays(-3);
            await service.ChangeAsync(b=>
            {
                b.RestOverrides.Clear();b.RestOverrides[qaMonday.AddDays(5).ToString("yyyy-MM-dd")]=false;b.RestOverrides[qaMonday.AddDays(6).ToString("yyyy-MM-dd")]=true;
                foreach(var entry in new[]{(0,9,"周会"),(0,11,"需求评审"),(0,14,"界面设计"),(0,16,"健身"),(1,8,"早间复盘"),(1,15,"文档整理"),(1,19,"看电影"),(2,8,"项目会议"),(2,14,"方案评审"),(2,19,"运动"),(3,10,"设计走查"),(3,15,"版本测试"),(3,20,"和小天聊天"),(4,9,"周报整理"),(4,14,"用户访谈"),(4,18,"买礼物"),(5,10,"学习新技能"),(5,14,"整理房间"),(5,20,"打游戏"),(6,9,"和家人视频"),(6,14,"赏月"),(6,19,"吃月饼"),(6,21,"听歌放松")})
                {
                    var item=new ReminderItem{Calendar=true,Title=entry.Item3,Start=qaMonday.AddDays(entry.Item1).AddHours(entry.Item2),HasTime=true,ReminderCreated=entry.Item2%2==0,Enabled=entry.Item2%2==0};b.Items.Add(item);qaEvents.Add(item.Id);
                }
            });
            Set("_date",qaMonday.AddDays(2));window.UpdateLayout();Snapshot(window,"03-week-reference-density",true);
            await service.ChangeAsync(b=>{b.Items.RemoveAll(i=>qaEvents.Contains(i.Id));b.RestOverrides=qaOverrides;});Set("_date",day);
            await service.ChangeAsync(b=>b.WeekView=false);await Task.Delay(100);window.UpdateLayout();
            Check(Tree(window).OfType<FrameworkElement>().Any(e=>e.Name=="ViewMonth")&&Tree(window).OfType<FrameworkElement>().Any(e=>e.Name=="ViewWeek"),"A02 month and week view buttons keep their labels");
            string Summary()=>string.Concat(Tree((DependencyObject)((Button)Named(window,"ModifyDates")).Content).OfType<TextBlock>().Select(t=>t.Text));
            await RunScheduleDesignQa(window,service,path,checks,day);
            window.Navigate(true);Snapshot(window,"06-alarms",true);var alarmBody=(ScrollViewer)typeof(PlannerWindow).GetField("_body",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!;var newAlarm=(Button)Named(window,"NewAlarm");var titleBar=(Grid)Named(window,"PlannerTitleBar");Rect addBounds=newAlarm.TransformToAncestor(window).TransformBounds(new Rect(0,0,newAlarm.ActualWidth,newAlarm.ActualHeight));Rect titleBounds=titleBar.TransformToAncestor(window).TransformBounds(new Rect(0,0,titleBar.ActualWidth,titleBar.ActualHeight));Check(newAlarm.Width==190&&newAlarm.Height==48&&addBounds.Top>=titleBounds.Bottom,"new reminder is a larger body action separated from window controls");Check(!Tree(window).OfType<Grid>().Any(g=>g.Name=="AlarmColumns")&&!Tree(window).OfType<TextBlock>().Any(t=>t.Text=="名称 / 规则"||t.Text=="下次提醒"),"alarm page removes the traditional table header");var initialCountdown=(Border)Named(window,"CountdownPanel");Check(initialCountdown.ActualWidth>=alarmBody.ViewportWidth-20,"running countdown uses the full content width");Check(((Grid)Named(window,"MyAlarmGrid")).Children.Count==1&&((Grid)Named(window,"CalendarAlarmGrid")).Children.Count==2,"initial manual and calendar reminders use direct card grids");Check(Tree(window).OfType<Button>().Any(b=>b.Name=="NewAlarm"&&b.Content is StackPanel label&&label.Children.OfType<TextBlock>().Any(t=>t.Text=="新建提醒")),"A06 alarm page keeps one unified new-reminder action");Click(window,"NewAlarm");var unifiedEditor=(Grid)Named(window,"PlannerEditorLayout");Check(Tree(unifiedEditor).OfType<Button>().Count(b=>b.Content is StackPanel label&&label.Children.OfType<TextBlock>().Any(t=>t.Text is "闹钟" or "倒计时"))==2,"new reminder still opens the shared alarm/countdown editor");Click(window,"EditorClose");
            var denseAlarmIds=new List<Guid>();var denseCalendarIds=new List<Guid>();DateTime qaNow=DateTime.Now,qaToday=qaNow.Date;
            await service.ChangeAsync(b=>
            {
                var previewAlarms=new[]
                {
                    new ReminderItem{Title="单次提醒",Start=qaToday.AddDays(1).AddHours(7),Repeat=ReminderRepeat.Once},
                    new ReminderItem{Title="六日正向摘要",Start=qaToday.AddHours(20),Repeat=ReminderRepeat.Weekly,Weekdays=[DayOfWeek.Monday,DayOfWeek.Tuesday,DayOfWeek.Wednesday,DayOfWeek.Thursday,DayOfWeek.Friday,DayOfWeek.Saturday]},
                    new ReminderItem{Title="工作日提醒",Start=qaToday.AddHours(9),Repeat=ReminderRepeat.Workdays},
                    new ReminderItem{Title="休息日提醒",Start=qaToday.AddHours(22),Repeat=ReminderRepeat.RestDays},
                    new ReminderItem{Title="指定日期提醒",Start=qaToday.AddDays(12).AddHours(18),Repeat=ReminderRepeat.Dates,Dates=[qaToday.AddDays(12)]},
                };
                foreach(var alarm in previewAlarms){denseAlarmIds.Add(alarm.Id);b.Items.Add(alarm);}
                for(int n=0;n<4;n++){var schedule=new ReminderItem{Calendar=true,Title="日历预览 "+(n+1),Start=qaToday.AddDays(n+2).AddHours(10+n),Repeat=ReminderRepeat.Once,ReminderCreated=true,Enabled=true};denseCalendarIds.Add(schedule.Id);b.Items.Add(schedule);}
            });
            window.UpdateLayout();Snapshot(window,"06-alarms-dense",true);var denseAlarmBody=(ScrollViewer)typeof(PlannerWindow).GetField("_body",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!;var myGrid=(Grid)Named(window,"MyAlarmGrid");var calendarGridView=(Grid)Named(window,"CalendarAlarmGrid");var myCards=Tree(myGrid).OfType<Border>().Where(b=>b.Name.StartsWith("AlarmCard",StringComparison.Ordinal)).ToList();var calendarCards=Tree(calendarGridView).OfType<Border>().Where(b=>b.Name.StartsWith("CalendarAlarmCard",StringComparison.Ordinal)).ToList();Check(myCards.Count==6&&calendarCards.Count==6&&myGrid.Children.Cast<UIElement>().Select((element,index)=>(Grid.GetRow(element),Grid.GetColumn(element))).SequenceEqual(Enumerable.Range(0,6).Select(index=>(index/2,index%2==0?0:2))),"manual and calendar reminders fill strict two-column grids left to right");Check(myCards.All(card=>card.Child is Grid layout&&layout.RowDefinitions.Count==2)&&calendarCards.All(card=>card.Child is Grid layout&&layout.RowDefinitions.Count==2),"every reminder card keeps exactly two information layers");double[] nextStarts=myCards.Select(card=>Tree(card).OfType<TextBlock>().First(t=>t.Name=="AlarmNext").TransformToAncestor(card).Transform(new Point()).X).ToArray();Check(nextStarts.Max()-nextStarts.Min()<1,"all manual alarm next-time labels share one fixed X origin");Check(!Tree(myGrid).OfType<TextBlock>().Any(t=>t.Name=="AlarmNext"&&t.Text.Contains("下次")),"next-time summaries omit the redundant next label");var periods=Tree(myGrid).OfType<TextBlock>().Where(t=>t.Name=="AlarmPeriod").Select(t=>t.Text).ToHashSet();Check(new[]{"每天","单次","每周一二三四五六","工作日","休息日","指定日期"}.All(periods.Contains)&&periods.All(period=>!period.Contains("除")),"weekly period uses the complete positive weekday summary without reverse wording");var weeklySummary=typeof(PlannerWindow).GetMethod("WeeklySummary",BindingFlags.NonPublic|BindingFlags.Static)!;string W(params DayOfWeek[] days)=>(string)weeklySummary.Invoke(null,new object[]{days})!;Check(W(DayOfWeek.Monday)=="每周一"&&W(DayOfWeek.Monday,DayOfWeek.Wednesday,DayOfWeek.Friday)=="每周一三五"&&W(DayOfWeek.Monday,DayOfWeek.Wednesday,DayOfWeek.Friday,DayOfWeek.Sunday)=="每周一三五日"&&W(DayOfWeek.Monday,DayOfWeek.Tuesday,DayOfWeek.Wednesday,DayOfWeek.Thursday,DayOfWeek.Friday)=="每周一二三四五"&&W(DayOfWeek.Monday,DayOfWeek.Tuesday,DayOfWeek.Wednesday,DayOfWeek.Thursday,DayOfWeek.Friday,DayOfWeek.Saturday)=="每周一二三四五六"&&W(DayOfWeek.Monday,DayOfWeek.Tuesday,DayOfWeek.Wednesday,DayOfWeek.Thursday,DayOfWeek.Friday,DayOfWeek.Sunday)=="每周一二三四五日"&&W(DayOfWeek.Monday,DayOfWeek.Tuesday,DayOfWeek.Wednesday,DayOfWeek.Thursday,DayOfWeek.Friday,DayOfWeek.Saturday,DayOfWeek.Sunday)=="每天","weekly summary lists selected weekdays in Monday-to-Sunday order and normalizes all seven to daily");Check(calendarCards.All(card=>Tree(card).OfType<Border>().Any(b=>b.Name=="CalendarSource")),"calendar reminder cards use the subtle calendar source tag");
            var formatNext=typeof(PlannerWindow).GetMethod("FormatNextOccurrence",BindingFlags.NonPublic|BindingFlags.Static)!;DateTime formatBase=new(2026,9,16,12,0,0);string F(DateTime value)=>(string)formatNext.Invoke(null,new object[]{value,formatBase})!;Check(F(new(2026,9,16,18,0,0))=="今天 18:00"&&F(new(2026,9,17,7,0,0))=="明天 07:00"&&F(new(2026,9,18,8,30,0))=="后天 08:30"&&F(new(2026,9,19,20,0,0))=="周六 20:00"&&F(new(2026,9,21,9,0,0))=="下周一 09:00"&&F(new(2026,9,28,18,0,0))=="9月28日 18:00"&&F(new(2027,1,2,8,0,0))=="2027/1/2 08:00","next occurrence formatter covers today through cross-year without a next prefix");
            var syncCalendar=service.Book.Items.First(i=>i.Calendar&&i.ReminderCreated==true&&i.Enabled);var syncCard=(Border)Named(window,"CalendarAlarmCard"+syncCalendar.Id.ToString("N"));var syncToggle=Tree(syncCard).OfType<CheckBox>().Single(c=>c.Name=="AlarmEnabled");syncToggle.IsChecked=false;syncToggle.RaiseEvent(new RoutedEventArgs(CheckBox.ClickEvent));await Task.Delay(200);Check(!service.Book.Items.Single(i=>i.Id==syncCalendar.Id).Enabled,"calendar card toggle writes the same schedule reminder state");await service.ChangeAsync(b=>b.Items.Single(i=>i.Id==syncCalendar.Id).Enabled=true);window.UpdateLayout();syncCard=(Border)Named(window,"CalendarAlarmCard"+syncCalendar.Id.ToString("N"));Check(Tree(syncCard).OfType<CheckBox>().Single(c=>c.Name=="AlarmEnabled").IsChecked==true,"calendar editor state changes render back into the card toggle");
            var editableCard=Tree((Grid)Named(window,"MyAlarmGrid")).OfType<Border>().First(b=>b.Name.StartsWith("AlarmCard",StringComparison.Ordinal));editableCard.RaiseEvent(new System.Windows.Input.MouseButtonEventArgs(System.Windows.Input.Mouse.PrimaryDevice,Environment.TickCount,System.Windows.Input.MouseButton.Left){RoutedEvent=UIElement.MouseLeftButtonUpEvent,Source=editableCard});Check(Tree(window).OfType<Grid>().Any(g=>g.Name=="PlannerEditorLayout"),"clicking a manual alarm card opens the existing alarm editor");Click(window,"EditorClose");window.UpdateLayout();
            var multiDateCalendar=new ReminderItem{Title="多日期日程",Calendar=true,Start=qaToday.AddDays(-1).AddHours(17),Repeat=ReminderRepeat.Dates,Dates=[qaToday.AddDays(-1),qaToday.AddDays(3)],ReminderCreated=true,Enabled=true};denseCalendarIds.Add(multiDateCalendar.Id);await service.ChangeAsync(b=>b.Items.Add(multiDateCalendar));window.UpdateLayout();string expectedMultiNext=F(qaToday.AddDays(3).AddHours(17));Check(Tree(window).OfType<Border>().Any(b=>b.Name=="CalendarAlarmCard"+multiDateCalendar.Id.ToString("N"))&&Tree((Border)Named(window,"CalendarAlarmCard"+multiDateCalendar.Id.ToString("N"))).OfType<TextBlock>().Any(t=>t.Name=="AlarmNext"&&t.Text==expectedMultiNext),"multi-date calendar reminder advances to its remaining future date");await service.ChangeAsync(b=>b.Items.Single(i=>i.Id==multiDateCalendar.Id).Dates=[qaToday.AddDays(-1)]);window.UpdateLayout();Check(!Tree(window).OfType<Border>().Any(b=>b.Name=="CalendarAlarmCard"+multiDateCalendar.Id.ToString("N")),"calendar reminder leaves the list only after its final date has passed");
            var expiredManual=new ReminderItem{Title="已结束仍保留",Calendar=false,Start=qaToday.AddDays(-1).AddHours(8),Repeat=ReminderRepeat.Once,Enabled=false};var expiredCalendar=new ReminderItem{Title="已结束日历提醒",Calendar=true,Start=qaToday.AddDays(-1).AddHours(8),Repeat=ReminderRepeat.Once,ReminderCreated=true,Enabled=true};await service.ChangeAsync(b=>{b.Items.Add(expiredManual);b.Items.Add(expiredCalendar);});window.UpdateLayout();Check(Tree(window).OfType<Border>().Any(b=>b.Name=="AlarmCard"+expiredManual.Id.ToString("N"))&&!Tree(window).OfType<Border>().Any(b=>b.Name=="CalendarAlarmCard"+expiredCalendar.Id.ToString("N")),"completed manual alarm remains as a closed card while completed calendar reminder leaves the list");var expiredCard=(Border)Named(window,"AlarmCard"+expiredManual.Id.ToString("N"));Check(Tree(expiredCard).OfType<TextBlock>().Any(t=>t.Name=="AlarmNext"&&t.Text=="已结束")&&!Tree(expiredCard).OfType<CheckBox>().Single(c=>c.Name=="AlarmEnabled").IsEnabled,"finished finite alarm stays editable with a disabled OFF toggle");await service.ChangeAsync(b=>{b.Items.RemoveAll(i=>i.Id==expiredManual.Id||i.Id==expiredCalendar.Id);});
            await service.ChangeAsync(b=>b.Items.RemoveAll(i=>i.Id==denseCalendarIds[0]));window.UpdateLayout();var oddCalendarGrid=(Grid)Named(window,"CalendarAlarmGrid");UIElement oddLast=oddCalendarGrid.Children.Cast<UIElement>().Last();Check(oddCalendarGrid.Children.Count%2==1&&Grid.GetColumn(oddLast)==0,"an odd final calendar reminder stays left aligned with an empty right column");
            Check(denseAlarmBody.ScrollableHeight>0,"dense two-column reminder grids scroll inside the fixed page");denseAlarmBody.ScrollToBottom();window.UpdateLayout();Snapshot(window,"06-alarms-dense-bottom",true);Check(denseAlarmBody.VerticalOffset>0&&Tree(window).OfType<TextBlock>().Any(t=>t.Text=="日历提醒"),"dense alarm list reaches calendar reminders without clipping cards");await service.ChangeAsync(b=>b.Items.RemoveAll(i=>denseAlarmIds.Contains(i.Id)||denseCalendarIds.Contains(i.Id)));window.UpdateLayout();
            Edit(null,false);var reminderEditor=(Grid)Named(window,"PlannerEditorLayout");Check(!Tree(reminderEditor).OfType<TextBlock>().Any(t=>t.Text=="新建提醒")&&Tree(reminderEditor).OfType<Button>().Any(b=>b.Content is StackPanel label&&label.Children.OfType<TextBlock>().Any(t=>t.Text=="闹钟")),"reminder editor header is only the alarm/countdown segmented control");Check(((TextBox)Named(window,"ReminderTitle")).MaxLength==30&&Tree(window).OfType<TextBlock>().Any(t=>t.Text=="0/30"),"A38 scheduled alarm name is limited to 30 characters");Snapshot(window,"07-new-alarm",true);
            var alarmTitle=(TextBox)Named(window,"ReminderTitle");alarmTitle.Text=new string('字',31);if(alarmTitle.Text.Length>30){int before=service.Book.Items.Count;Click(window,"SaveReminder");await Task.Delay(100);Check(service.Book.Items.Count==before&&Tree(window).OfType<TextBlock>().Any(t=>t.Text.Contains("名称最多30字")),"A38 programmatic over-limit reminder name is rejected at save");}else Check(alarmTitle.Text.Length==30,"A38 alarm input itself clamps over-limit text");
            Click(window,"EditorClose");var legacyAlarm=new ReminderItem{Title=new string('旧',40),Start=DateTime.Today.AddDays(1).AddHours(7)};await service.ChangeAsync(b=>b.Items.Add(legacyAlarm));Edit(legacyAlarm,false);Check(((TextBox)Named(window,"ReminderTitle")).Text==legacyAlarm.Title,"A38 old longer alarm name is not silently trimmed");Click(window,"SaveReminder");await Task.Delay(200);Check(service.Book.Items.Single(i=>i.Id==legacyAlarm.Id).Title.Length==40,"A38 unchanged old alarm name survives editing");Edit(null,false);
            Tree(window).OfType<Button>().First(b=>Equals(b.Content,"每天")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));_=window.Dispatcher.BeginInvoke(new Action(()=>{var modal=Application.Current.Windows.OfType<DateSelectionWindow>().Single(w=>w.Owner==window&&w.IsVisible);Click(modal,"CancelDates");}),System.Windows.Threading.DispatcherPriority.ContextIdle);Tree(window).OfType<Button>().First(b=>Equals(b.Content,"指定日期")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(((System.Windows.Controls.ComboBox)Named(window,"ReminderRepeat")).SelectedIndex==(int)ReminderRepeat.Daily&&!Tree(window).OfType<Button>().Any(b=>b.Name=="ModifyDates"&&b.IsVisible),"cancelling the first specified-date picker restores the previous cycle");
            DateTime alarmSecond=day.AddDays(2);_=window.Dispatcher.BeginInvoke(new Action(()=>{var modal=Application.Current.Windows.OfType<DateSelectionWindow>().Single(w=>w.Owner==window&&w.IsVisible);Click(modal,"Date"+alarmSecond.ToString("yyyyMMdd"));Click(modal,"ConfirmDates");}),System.Windows.Threading.DispatcherPriority.ContextIdle);Tree(window).OfType<Button>().First(b=>Equals(b.Content,"指定日期")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(((System.Windows.Controls.ComboBox)Named(window,"ReminderRepeat")).SelectedIndex==(int)ReminderRepeat.Dates&&Tree(window).OfType<Button>().Any(b=>b.Name=="ModifyDates"&&b.IsVisible)&&Summary().Contains(alarmSecond.ToString("M月d日")),"confirming the first specified-date picker immediately reveals the reusable full-row date summary");Snapshot(window,"07-new-alarm-dates",true);Click(window,"EditorClose");
            DateTime[] alarmSameYear=Enumerable.Range(0,5).Select(n=>new DateTime(2026,9,17).AddDays(n)).Reverse().ToArray();Edit(new ReminderItem{Title="指定日期摘要",Start=alarmSameYear.Min().AddHours(9),Repeat=ReminderRepeat.Dates,Dates=alarmSameYear.ToList()},false);Check(Summary()=="9月17日9月18日9月19日9月20日+1天","alarm same-year summary sorts dates and displays four plus the undisplayed count");Click(window,"EditorClose");DateTime[] alarmCrossYear=[new(2027,1,5),new(2026,12,31),new(2027,1,1),new(2027,1,3),new(2027,1,4)];Edit(new ReminderItem{Title="跨年摘要",Start=alarmCrossYear.Min().AddHours(9),Repeat=ReminderRepeat.Dates,Dates=alarmCrossYear.ToList()},false);Check(Summary()=="2026/12/312027/01/012027/01/03+2天","alarm cross-year summary sorts dates and displays three plus the undisplayed count");Click(window,"EditorClose");Edit(null,false);
            Tree(window).OfType<Button>().First(b=>Equals(b.Content,"每周")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Tree(window).OfType<Button>().First(b=>Equals(b.Content,"一")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Tree(window).OfType<Button>().First(b=>Equals(b.Content,"三")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));((TextBox)Named(window,"ReminderTitle")).Text="每周提醒";Click(window,"SaveReminder");await Task.Delay(200);var weeklyAlarm=service.Book.Items.Last();Check(weeklyAlarm.Repeat==ReminderRepeat.Weekly&&weeklyAlarm.Weekdays.OrderBy(d=>d).SequenceEqual(new[]{DayOfWeek.Monday,DayOfWeek.Wednesday}),"weekly alarm saves the selected lightweight weekday chips");Edit(null,false);
            Tree(window).OfType<Button>().First(b=>Equals(b.Content,"工作日")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));((TextBox)Named(window,"ReminderTitle")).Text="工作日提醒";Click(window,"SaveReminder");await Task.Delay(200);Check(service.Book.Items.Last().Repeat==ReminderRepeat.Workdays,"A39 workday chip saves the effective workday repeat rule");Edit(null,false);
            Tree(window).OfType<Button>().First(b=>Equals(b.Content,"休息日")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));((TextBox)Named(window,"ReminderTitle")).Text="休息日提醒";Click(window,"SaveReminder");await Task.Delay(200);Check(service.Book.Items.Last().Repeat==ReminderRepeat.RestDays,"A39 restday chip saves the effective restday repeat rule");Edit(null,false);
            var modeEditor=(Grid)Named(window,"PlannerEditorLayout");var modeCard=(Border)VisualTreeHelper.GetParent(modeEditor);var alarmClose=(Button)Named(window,"EditorClose");Rect alarmCloseBounds=alarmClose.TransformToAncestor(modeCard).TransformBounds(new Rect(0,0,alarmClose.ActualWidth,alarmClose.ActualHeight));var countdownButton=Tree(window).OfType<Button>().First(b=>b.Content is StackPanel label&&label.Children.OfType<TextBlock>().Any(t=>t.Text=="倒计时"));countdownButton.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));window.UpdateLayout();var countdownClose=(Button)Named(window,"EditorClose");Rect countdownCloseBounds=countdownClose.TransformToAncestor(modeCard).TransformBounds(new Rect(0,0,countdownClose.ActualWidth,countdownClose.ActualHeight));Check(Math.Abs(countdownCloseBounds.Left-alarmCloseBounds.Left)<1&&Math.Abs(countdownCloseBounds.Top-alarmCloseBounds.Top)<1,"alarm/countdown switch keeps the shared header and Close fixed");Snapshot(window,"08-new-countdown",true);
            Check(((TextBox)Named(window,"ReminderTitle")).MaxLength==30&&Tree(window).OfType<TextBlock>().Any(t=>t.Text=="0/30"),"A38 countdown name shares the 30 character limit");
            var plannerShell=(Grid)typeof(PlannerWindow).GetField("_shell",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!;var editorCard=(Border)((Grid)plannerShell.Children[plannerShell.Children.Count-1]).Children[0];
            var countdownPresets=Tree(window).OfType<Button>().Where(b=>b.Content is string s&&new[]{"5分钟","15分钟","30分钟","1小时","2小时"}.Contains(s)).ToList();
            bool FitsEditor(FrameworkElement element){Rect bounds=element.TransformToAncestor(editorCard).TransformBounds(new Rect(0,0,element.ActualWidth,element.ActualHeight));return bounds.Left>=0&&bounds.Right<=editorCard.ActualWidth;}
            Check(countdownPresets.Count==5&&countdownPresets.All(FitsEditor)&&new[]{"CountdownHours","CountdownMinutes","CountdownSeconds"}.Select(n=>Named(window,n)).All(FitsEditor),"A16 five countdown presets and all three roller controls fit inside the editor");
            void Digits(string h,string m,string s){((TextBox)Named(window,"CountdownHours")).Text=h;((TextBox)Named(window,"CountdownMinutes")).Text=m;((TextBox)Named(window,"CountdownSeconds")).Text=s;}
            foreach(var preset in new[]{("5分钟",300),("15分钟",900),("30分钟",1800),("1小时",3600),("2小时",7200)}){Tree(window).OfType<Button>().First(b=>Equals(b.Content,preset.Item1)).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));int h=int.Parse(((TextBox)Named(window,"CountdownHours")).Text),m=int.Parse(((TextBox)Named(window,"CountdownMinutes")).Text),sec=int.Parse(((TextBox)Named(window,"CountdownSeconds")).Text);Check(h*3600+m*60+sec==preset.Item2,"A16 preset "+preset.Item1);if(preset.Item1=="30分钟")Snapshot(window,"08-countdown-30");}
            Tree(window).OfType<Button>().First(b=>Equals(b.Content,"30分钟")).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));((TextBox)Named(window,"CountdownMinutes")).Text="31";Check(!Equals(Tree(window).OfType<Button>().First(b=>Equals(b.Content,"30分钟")).BorderBrush,PlannerTheme.Accent),"manual duration edit clears the matching quick preset");
            foreach(string part in new[]{"CountdownHours","CountdownMinutes","CountdownSeconds"}){var input=(TextBox)Named(window,part);input.Text="01";input.RaiseEvent(new System.Windows.Input.MouseWheelEventArgs(System.Windows.Input.Mouse.PrimaryDevice,0,120){RoutedEvent=System.Windows.Input.Mouse.PreviewMouseWheelEvent});Check(input.Text=="02","A16 wheel "+part);}
            int count=service.Book.Items.Count;Digits("0","0","0");Check(!((Button)Named(window,"SaveReminder")).IsEnabled,"zero duration disables Start instead of submitting");Click(window,"SaveReminder");await Task.Delay(100);Check(service.Book.Items.Count==count,"A17 zero cannot create a countdown");Digits("24","30","01");await Task.Delay(50);Check(((TextBox)Named(window,"CountdownMinutes")).Text=="00"&&((TextBox)Named(window,"CountdownSeconds")).Text=="00"&&!((TextBox)Named(window,"CountdownMinutes")).IsEnabled&&!((TextBox)Named(window,"CountdownSeconds")).IsEnabled,"24 hours immediately zeroes and disables minutes and seconds");((TextBox)Named(window,"CountdownHours")).Text="23";Check(((TextBox)Named(window,"CountdownMinutes")).IsEnabled&&((TextBox)Named(window,"CountdownSeconds")).IsEnabled,"dropping below 24 restores minute and second editing");Digits("24","0","0");Click(window,"SaveReminder");await Task.Delay(250);Check(service.Book.Items.Count==count+1&&service.Book.Items.Last().DurationSeconds==86400,"A17 accepts exactly 24 hours with optional empty name");
            var timer=service.Book.Items.Last();await service.ChangeAsync(b=>ReminderEngine.Pause(b,timer.Id,DateTime.Now));var frozen=service.Book.Items.Last().PausedSeconds;await Task.Delay(100);Check(frozen==service.Book.Items.Last().PausedSeconds,"A18 pause freezes remaining");await service.ChangeAsync(b=>ReminderEngine.Resume(b,timer.Id,DateTime.Now));Check(service.Book.Items.Last().PausedSeconds==null,"A18 resume");
            DateTime at=DateTime.Now.AddMinutes(20);await service.ChangeAsync(b=>{b.Items.Clear();b.Occurrences.Clear();for(int n=0;n<2;n++){var i=new ReminderItem{Calendar=true,Title="测试日程"+n,Notes="准备演示资料",Start=at.AddMinutes(n),ReminderCreated=true,EarlyEnabled=true,CheckedThrough=DateTime.Now};i.CheckedThrough=i.Start;b.Items.Add(i);b.Occurrences.Add(new(){RuleId=i.Id,At=i.Start,Phase=ReminderPhase.Early});}});
            _reminders=service;var foreground=PlannerQaForeground();RefreshReminderCardCore(true);Check(PlannerQaForeground()==foreground,"reminder does not steal focus");Snapshot(_reminderCard!,"09-early-reminder");
            Click(_reminderCard!,"AcknowledgeReminder");await Task.Delay(200);RefreshReminderCardCore(true);Check(service.Book.Occurrences.Count(o=>o.Phase==ReminderPhase.AcknowledgedEarly)==1,"A19 acknowledge one early retains due");
            Click(_reminderCard!,"AcknowledgeReminder");await Task.Delay(200);RefreshReminderCardCore(true);Snapshot(_reminderCard!,"10-capsule");Check(service.Book.Occurrences.All(o=>o.Phase==ReminderPhase.AcknowledgedEarly),"A22 both instances combined");
            var sameCard=_reminderCard!;var sameSurface=sameCard.Surface;var sameHeader=sameCard.Header;
            Check(sameCard.ActualHeight<=80&&!sameCard.ShowInTaskbar&&sameCard.Owner==this,"quick card is compact owned pet surface without taskbar icon");
            var workArea=GetQuickActionsWorkArea();Left=workArea.Left+workArea.Width/2-Width/2;Top=workArea.Top+30;RefreshReminderCardCore(true);await Task.Delay(100);
            double baseTop=sameCard.Top,baseLeft=sameCard.Left;
            Click(_reminderCard!,"ToggleQuickReminder");await Task.Delay(230);Snapshot(_reminderCard!,"11-capsule-expanded");
            Check(ReferenceEquals(sameCard,_reminderCard)&&ReferenceEquals(sameSurface,_reminderCard!.Surface)&&ReferenceEquals(sameHeader,_reminderCard.Header),"expansion retains same host border and summary header");
            Click(sameCard,"DismissQuickReminder");Snapshot(sameCard,"11-capsule-closed");Check(service.Book.Occurrences.All(o=>o.Phase==ReminderPhase.AcknowledgedEarly)&&Named(sameCard,"UndoQuickDismiss") is Button,"closing quick reminder keeps due occurrences and offers undo");
            Click(sameCard,"UndoQuickDismiss");RefreshReminderCardCore(true);Check(sameCard.IsVisible&&service.Book.Occurrences.All(o=>o.Phase==ReminderPhase.AcknowledgedEarly),"undo restores the quick reminder without altering occurrences");
            Check(sameCard.ActualHeight>100&&Math.Abs(sameCard.Top-baseTop)<1,"expansion grows downward with fixed top anchor");
            Click(sameCard,"ToggleQuickReminder");await Task.Delay(230);
            Check(sameCard.ActualHeight<=80&&service.Book.Occurrences.All(o=>o.Phase==ReminderPhase.AcknowledgedEarly),"collapse does not cancel or acknowledge the occurrence");
            _isWindowDragging=true;Left+=35;Top+=15;RefreshReminderCardCore(true);await Task.Delay(100);
            Check(sameCard.IsVisible&&Math.Abs(sameCard.Left-baseLeft-35)<2&&Math.Abs(sameCard.Top-baseTop-15)<2,"quick card follows pet during drag");_isWindowDragging=false;
            Click(sameCard,"ToggleQuickReminder");await Task.Delay(230);
            Click(_reminderCard!,"CancelOccurrence");await Task.Delay(200);Check(service.Book.Occurrences.Count(o=>o.Phase==ReminderPhase.Cancelled)==1,"A21 cancels only selected instance");
            await service.ChangeAsync(b=>ReminderEngine.Advance(b,at.AddMinutes(2)));RefreshReminderCardCore(true);Snapshot(_reminderCard!,"12-due-reminder");Check(!Tree(_reminderCard!).OfType<Button>().Any(b=>b.Name=="CancelOccurrence"),"A24 due only acknowledge and snooze");
            RefreshReminderCardCore(false);Check(!_reminderCard!.IsVisible,"safety hides reminder without dropping data");
            Check(!PlannerPresentationSafe(new(false,null,false))&&!PlannerPresentationSafe(new(true,"YuanShen",false))&&!PlannerPresentationSafe(new(true,"app",true)),"unknown foreground game fullscreen suppress reminders");
            var stored=await new ReminderStore(new LocalAppPaths(Path.Combine(path,"UserData"))).LoadAsync();Check(stored.Occurrences.Any(o=>o.Phase==ReminderPhase.Cancelled),"A27 cancellation survives reload");
            using(var verify=new ReminderService(new LocalAppPaths(Path.Combine(path,"UserData")))){await verify.LoadAsync();Check(verify.Book.Occurrences.Any(o=>o.Phase==ReminderPhase.Cancelled),"A27 service reload preserves cancellation");}
            // Scope actions operate on the original group ID, never on copied date records.
            await service.ChangeAsync(b=>{b.Items.Clear();b.Occurrences.Clear();
                b.Items.Add(new ReminderItem{Calendar=true,Title="今天会议",Notes="项目讨论",Start=day.AddHours(8),Repeat=ReminderRepeat.Once,ReminderCreated=true});
                b.Items.Add(new ReminderItem{Calendar=true,Title="未来阅读",Notes="备注关键词",HasTime=false,Start=day.AddDays(2),Repeat=ReminderRepeat.Once,ReminderCreated=true});
                b.Items.Add(new ReminderItem{Calendar=true,Title="已经结束",Start=DateTime.Today.AddDays(-2).AddHours(10),Repeat=ReminderRepeat.Once,ReminderCreated=true});
                DateTime multiBase=DateTime.Today.AddDays(-2);b.Items.Add(new ReminderItem{Calendar=true,Title="多日期日程",Notes="多日期备注",Start=multiBase.AddHours(23),Dates=Enumerable.Range(0,10).Select(n=>multiBase.AddDays(n)).ToList(),Repeat=ReminderRepeat.Dates,ReminderCreated=true,EarlyEnabled=false});
                b.Items.Add(new ReminderItem{Calendar=true,Title="历史多日期",Start=DateTime.Today.AddDays(-6).AddHours(14),Dates=[DateTime.Today.AddDays(-6),DateTime.Today.AddDays(-3)],Repeat=ReminderRepeat.Dates,ReminderCreated=true,EarlyEnabled=false});});
            window.Navigate(false);typeof(PlannerWindow).GetMethod("OpenManage",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(window,null);window.UpdateLayout();
            Check(Equals(typeof(PlannerWindow).GetField("_manageFilter",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!.ToString(),"Active"),"management page explicitly initializes its default filter");
            Check(Named(window,"ManageSearch") is TextBox&&!Tree(window).OfType<CheckBox>().Any()&&!Tree(window).OfType<TextBlock>().Any(t=>t.Text.Contains("共 ")||t.Text.Contains("已选")),"management page removes batch selection controls and exposes title/notes search");
            var activeGrid=(Grid)Named(window,"ManageScheduleGrid");Check(activeGrid.Children.Count==3&&Tree(window).OfType<Button>().Count(b=>b.Name.StartsWith("EditSchedule",StringComparison.Ordinal))==3,"active management view mixes single and multi-date schedules in time order");Snapshot(window,"22-manage-active");
            Click(window,"ManageFilterAll");window.UpdateLayout();var allGrid=(Grid)Named(window,"ManageScheduleGrid");Check(allGrid.Children.Count==5&&Tree(window).OfType<Button>().Count(b=>b.Name.StartsWith("EditSchedule",StringComparison.Ordinal))==5,"all management view includes ended single and ended multi-date schedules");
            var multiId=service.Book.Items.Single(i=>i.Title=="多日期日程").Id;Check(Tree(window).OfType<TextBlock>().Any(t=>t.Text=="多日期 · 10次")&&Tree(window).OfType<TextBlock>().Any(t=>t.Text=="已发生2次 · 未来8次")&&Tree(window).OfType<TextBlock>().Any(t=>t.Text=="+1天"),"multi-date card keeps total, past/future counts and seven-chip overflow consistent");
            TextBox managementSearch=(TextBox)Named(window,"ManageSearch");managementSearch.Text="备注关键词";window.UpdateLayout();Check(((Grid)Named(window,"ManageScheduleGrid")).Children.Count==1&&Tree(window).OfType<Button>().Count(b=>b.Name.StartsWith("EditSchedule",StringComparison.Ordinal))==1,"management search matches notes and narrows the card grid");
            managementSearch.Text="";Click(window,"ManageFilterEnded");window.UpdateLayout();var endedGrid=(Grid)Named(window,"ManageScheduleGrid");Check(endedGrid.Children.Count==2,"ended filter includes both finite ended schedule forms");
            var editId=service.Book.Items.Single(i=>i.Title=="已经结束").Id;Click(window,"EditSchedule"+editId.ToString("N"));window.UpdateLayout();Check(Named(window,"PlannerEditorLayout") is Grid,"management edit button opens the existing editor");Click(window,"EditorClose");window.UpdateLayout();
            await service.ChangeAsync(b=>{b.Items.Clear();b.Occurrences.Clear();});window.Navigate(false);
            DateSelectionWindow picker=new([day],day){Owner=window};picker.Show();picker.UpdateLayout();Click(picker,"Date"+day.AddDays(1).ToString("yyyyMMdd"));Check(picker.Selection.Count==2,"A13 direct date multiselect");
            picker.Selection.Clear();typeof(DateSelectionWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(picker,null);picker.UpdateLayout();var pickerGrid=Tree(picker).OfType<Grid>().First(g=>g.Children.OfType<Button>().Any(b=>b.Name.StartsWith("Date",StringComparison.Ordinal)));var dragStart=(Button)Named(picker,"Date"+day.AddDays(1).ToString("yyyyMMdd"));var dragEnd=(Button)Named(picker,"Date"+day.AddDays(4).ToString("yyyyMMdd"));Point dateDragFrom=dragStart.TransformToAncestor(pickerGrid).Transform(new Point(dragStart.ActualWidth/2,dragStart.ActualHeight/2));Point dateDragTo=dragEnd.TransformToAncestor(pickerGrid).Transform(new Point(dragEnd.ActualWidth/2,dragEnd.ActualHeight/2));
            typeof(DateSelectionWindow).GetField("_dragLastDay",BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(picker,null);typeof(DateSelectionWindow).GetMethod("ApplyDragPath",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(picker,new object[]{pickerGrid,dateDragFrom,dateDragTo});Check(picker.Selection.Count==4&&Enumerable.Range(1,4).All(n=>picker.Selection.Contains(day.AddDays(n))),"A13 drag selects every date along the path");typeof(DateSelectionWindow).GetField("_dragLastDay",BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(picker,null);typeof(DateSelectionWindow).GetMethod("ApplyDragPath",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(picker,new object[]{pickerGrid,dateDragTo,dateDragFrom});Check(picker.Selection.Count==0,"A13 reverse drag cancels every date again");picker.Selection.Clear();picker.Selection.Add(day.AddDays(2));picker.Selection.Add(day.AddDays(4));typeof(DateSelectionWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(picker,null);picker.UpdateLayout();pickerGrid=Tree(picker).OfType<Grid>().First(g=>g.Children.OfType<Button>().Any(b=>b.Name.StartsWith("Date",StringComparison.Ordinal)));dragStart=(Button)Named(picker,"Date"+day.AddDays(1).ToString("yyyyMMdd"));dragEnd=(Button)Named(picker,"Date"+day.AddDays(4).ToString("yyyyMMdd"));dateDragFrom=dragStart.TransformToAncestor(pickerGrid).Transform(new Point(dragStart.ActualWidth/2,dragStart.ActualHeight/2));dateDragTo=dragEnd.TransformToAncestor(pickerGrid).Transform(new Point(dragEnd.ActualWidth/2,dragEnd.ActualHeight/2));typeof(DateSelectionWindow).GetField("_dragLastDay",BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(picker,null);typeof(DateSelectionWindow).GetMethod("ApplyDragPath",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(picker,new object[]{pickerGrid,dateDragFrom,dateDragTo});Check(picker.Selection.Count==2&&picker.Selection.Contains(day.AddDays(1))&&picker.Selection.Contains(day.AddDays(3))&&!picker.Selection.Contains(day.AddDays(2))&&!picker.Selection.Contains(day.AddDays(4)),"A13 drag toggles mixed selected and unselected dates");Snapshot(picker,"14-date-picker");picker.Close();
            DateSelectionWindow defaultDates=new([],DateTime.Today){Owner=window};defaultDates.Show();defaultDates.UpdateLayout();var pickerTodayButton=(Button)Named(defaultDates,"Date"+DateTime.Today.ToString("yyyyMMdd"));Check(defaultDates.Selection.SetEquals([DateTime.Today])&&Equals(pickerTodayButton.Background,PlannerTheme.PrimaryFill)&&pickerTodayButton.Content is StackPanel,"date picker without an entry date selects today and keeps a separate today mark");Snapshot(defaultDates,"14-date-picker-today");var ordinaryPickerDate=(Button)Named(defaultDates,"Date"+DateTime.Today.AddDays(2).ToString("yyyyMMdd"));Check(Equals(ordinaryPickerDate.Background,Brushes.Transparent)&&ordinaryPickerDate.BorderThickness.Left==0,"ordinary date cells show only numbers without box borders");ordinaryPickerDate.RaiseEvent(new System.Windows.Input.MouseEventArgs(System.Windows.Input.Mouse.PrimaryDevice,Environment.TickCount){RoutedEvent=UIElement.MouseEnterEvent});Check(Equals(ordinaryPickerDate.Background,PlannerTheme.HoverBackground),"hover shows a light blue background");ordinaryPickerDate.RaiseEvent(new System.Windows.Input.MouseEventArgs(System.Windows.Input.Mouse.PrimaryDevice,Environment.TickCount){RoutedEvent=UIElement.MouseLeaveEvent});Click(defaultDates,"Date"+DateTime.Today.ToString("yyyyMMdd"));defaultDates.UpdateLayout();Check(defaultDates.Selection.Count==0&&Equals(pickerTodayButton.BorderBrush,PlannerTheme.Accent)&&pickerTodayButton.BorderThickness.Left==1,"today without selection uses a thin blue outline");Snapshot(defaultDates,"14-date-picker-today-only");defaultDates.Close();
            DateSelectionWindow clearedReopen=new([],DateTime.Today,false){Owner=window};clearedReopen.Show();clearedReopen.UpdateLayout();Check(clearedReopen.Selection.Count==0&&Tree(clearedReopen).OfType<TextBlock>().Any(t=>t.Text=="已选 0 天"),"an intentionally confirmed empty editor selection reopens empty rather than being reseeded");clearedReopen.Close();
            DateTime specifiedPickerDay=new(2026,9,20);DateSelectionWindow fromSpecifiedDay=new([specifiedPickerDay],specifiedPickerDay){Owner=window};fromSpecifiedDay.Show();fromSpecifiedDay.UpdateLayout();Check(fromSpecifiedDay.Selection.SetEquals([specifiedPickerDay])&&Equals(((Button)Named(fromSpecifiedDay,"Date20260920")).Background,PlannerTheme.PrimaryFill)&&Tree(fromSpecifiedDay).OfType<Button>().Any(b=>b.Name=="RemoveDate20260920"),"contextual add opens with the specified day selected and one removable chip");Snapshot(fromSpecifiedDay,"14-date-picker-specified-one");fromSpecifiedDay.Close();
            DateSelectionWindow twoDates=new([day,day.AddDays(2)],day){Owner=window};twoDates.Show();twoDates.UpdateLayout();Check(twoDates.Selection.Count==2&&!Tree(twoDates).OfType<Button>().Any(b=>b.Name=="ExpandDates")&&Tree(twoDates).OfType<Button>().Count(b=>b.Name.StartsWith("RemoveDate"))==2,"two selected dates fit on one line without a fold");Snapshot(twoDates,"14-date-picker-two");twoDates.Close();
            DateSelectionWindow justOver=new(Enumerable.Range(0,8).Select(n=>day.AddDays(n)),day){Owner=window};justOver.Show();justOver.UpdateLayout();var firstFold=(Button)Named(justOver,"ExpandDates");int shownChips=Tree(justOver).OfType<Button>().Count(b=>b.Name.StartsWith("RemoveDate"));Check(shownChips>0&&shownChips<8&&Equals(firstFold.Content,$"+{8-shownChips}⌄")&&justOver.Selection.Count==8,"more than one line folds according to measured chip width instead of a fixed first-three rule");double oldChipArea=((ScrollViewer)Named(justOver,"SelectedDateScroll")).ActualWidth;justOver.Width=420;justOver.UpdateLayout();int narrowShown=Tree(justOver).OfType<Button>().Count(b=>b.Name.StartsWith("RemoveDate"));Check(((ScrollViewer)Named(justOver,"SelectedDateScroll")).ActualWidth<oldChipArea&&narrowShown<shownChips&&Equals(((Button)Named(justOver,"ExpandDates")).Content,$"+{8-narrowShown}⌄"),"fold capacity recalculates when the actual chip container narrows");justOver.Width=470;justOver.UpdateLayout();Snapshot(justOver,"14-date-picker-just-over");justOver.Close();
            DateSelectionWindow oneLine=new(Enumerable.Range(0,shownChips).Select(n=>day.AddDays(n)),day){Owner=window};oneLine.Show();oneLine.UpdateLayout();Check(oneLine.Selection.Count==shownChips&&!Tree(oneLine).OfType<Button>().Any(b=>b.Name=="ExpandDates")&&Tree(oneLine).OfType<Button>().Count(b=>b.Name.StartsWith("RemoveDate"))==shownChips,"a nearly full single line still displays every selected date directly");Snapshot(oneLine,"14-date-picker-one-line");oneLine.Close();
            DateSelectionWindow manyDates=new(Enumerable.Range(0,12).Select(n=>day.AddDays(n)),day){Owner=window};manyDates.Show();manyDates.UpdateLayout();var selectedDateScroll=(ScrollViewer)typeof(DateSelectionWindow).GetField("_selectedScroll",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(manyDates)!;double foldedHeight=manyDates.ActualHeight;Check(manyDates.Selection.Count==12&&Named(manyDates,"ExpandDates") is Button&&selectedDateScroll.ScrollableHeight==0,"twelve selected dates start folded without a vertical scrollbar");Snapshot(manyDates,"14-date-picker-many-folded",true);Click(manyDates,"ExpandDates");manyDates.UpdateLayout();Check(manyDates.ActualHeight>foldedHeight&&selectedDateScroll.ScrollableHeight==0&&Tree(manyDates).OfType<Button>().Count(b=>b.Name.StartsWith("RemoveDate"))==12,"twelve dates expand inline, grow the modal and remain fully visible without scrolling");Snapshot(manyDates,"14-date-picker-many-expanded",true);
            DateTime removed=day.AddDays(6),added=day.AddDays(12);Click(manyDates,"RemoveDate"+removed.ToString("yyyyMMdd"));manyDates.UpdateLayout();Check(manyDates.Selection.Count==11&&!manyDates.Selection.Contains(removed)&&Equals(((Button)Named(manyDates,"Date"+removed.ToString("yyyyMMdd"))).Background,Brushes.Transparent),"expanded chip deletion immediately updates the calendar and count");Click(manyDates,"Date"+added.ToString("yyyyMMdd"));manyDates.UpdateLayout();Check(manyDates.Selection.Count==12&&manyDates.Selection.Contains(added)&&Equals(((Button)Named(manyDates,"Date"+added.ToString("yyyyMMdd"))).Background,PlannerTheme.PrimaryFill),"calendar remains interactive while dates are expanded");Click(manyDates,"CollapseDates");manyDates.UpdateLayout();Check(manyDates.Selection.Count==12&&Named(manyDates,"ExpandDates") is Button&&selectedDateScroll.ScrollableHeight==0,"collapse changes only the presentation and recomputes the remaining count");Click(manyDates,"ClearDates");manyDates.UpdateLayout();Check(manyDates.Selection.Count==0&&Tree(manyDates).OfType<TextBlock>().Any(t=>t.Text=="已选 0 天"),"clear removes only the temporary selection");manyDates.Close();
            DateSelectionWindow twentyDates=new(Enumerable.Range(0,20).Select(n=>day.AddDays(n)),day){Owner=window};twentyDates.Show();Click(twentyDates,"ExpandDates");twentyDates.UpdateLayout();var twentyScroll=(ScrollViewer)typeof(DateSelectionWindow).GetField("_selectedScroll",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(twentyDates)!;Check(twentyScroll.ScrollableHeight==0&&Tree(twentyDates).OfType<Button>().Count(b=>b.Name.StartsWith("RemoveDate"))==20,"twenty expanded dates remain naturally visible when the application height allows");Snapshot(twentyDates,"14-date-picker-twenty-expanded",true);twentyDates.Close();
            DateSelectionWindow extremeDates=new(Enumerable.Range(0,50).Select(n=>day.AddDays(n)),day){Owner=window};extremeDates.Show();Click(extremeDates,"ExpandDates");extremeDates.UpdateLayout();var extremeScroll=(ScrollViewer)typeof(DateSelectionWindow).GetField("_selectedScroll",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(extremeDates)!;Snapshot(extremeDates,"14-date-picker-extreme",true);Check(extremeScroll.ScrollableHeight>0&&extremeDates.ActualHeight<=window.ActualHeight-110&&((Button)Named(extremeDates,"ConfirmDates")).IsVisible,$"extreme expanded selection reserves about three chip rows and keeps Confirm inside Planner (scroll={extremeScroll.ScrollableHeight:0}, height={extremeDates.ActualHeight:0}, owner={window.ActualHeight:0}, max={extremeScroll.MaxHeight:0})");extremeScroll.ScrollToBottom();extremeDates.UpdateLayout();Snapshot(extremeDates,"14-date-picker-extreme-bottom");extremeDates.Close();
            DateTime[] acrossMonths=[new(2026,9,18),new(2026,9,20),new(2026,10,3),new(2026,10,16)];DateSelectionWindow crossMonthPicker=new(acrossMonths,new DateTime(2026,9,20)){Owner=window};crossMonthPicker.Show();crossMonthPicker.UpdateLayout();Check(crossMonthPicker.Selection.SetEquals(acrossMonths)&&Tree(crossMonthPicker).OfType<TextBlock>().Any(t=>t.Text=="已选 4 天"),"nonconsecutive selected dates across months all count in the summary");Click(crossMonthPicker,"NextDateMonth");crossMonthPicker.UpdateLayout();Check(crossMonthPicker.Selection.SetEquals(acrossMonths)&&Equals(((Button)Named(crossMonthPicker,"Date20261003")).Background,PlannerTheme.PrimaryFill)&&Equals(((Button)Named(crossMonthPicker,"Date20261016")).Background,PlannerTheme.PrimaryFill),"moving to October preserves September selections and highlights October dates");Snapshot(crossMonthPicker,"14-date-picker-cross-month");Click(crossMonthPicker,"PreviousDateMonth");crossMonthPicker.UpdateLayout();Check(crossMonthPicker.Selection.SetEquals(acrossMonths)&&Equals(((Button)Named(crossMonthPicker,"Date20260918")).Background,PlannerTheme.PrimaryFill),"moving back to September still preserves every selected month");crossMonthPicker.Close();
            DateTime[] originalPickerDates=[specifiedPickerDay];DateTime tentativeDay=specifiedPickerDay.AddDays(3);DateSelectionWindow cancelPicker=new(originalPickerDates,specifiedPickerDay){Owner=window};cancelPicker.Loaded+=(_,_)=>cancelPicker.Dispatcher.BeginInvoke(new Action(()=>{Click(cancelPicker,"Date"+tentativeDay.ToString("yyyyMMdd"));Click(cancelPicker,"CancelDates");}),System.Windows.Threading.DispatcherPriority.ContextIdle);bool? cancelled=cancelPicker.ShowDialog();Check(cancelled==false&&originalPickerDates.SequenceEqual([specifiedPickerDay])&&cancelPicker.Selection.Contains(tentativeDay),"Cancel discards temporary edits and preserves the caller's opening dates");
            DateSelectionWindow confirmPicker=new(originalPickerDates,specifiedPickerDay){Owner=window};confirmPicker.Loaded+=(_,_)=>confirmPicker.Dispatcher.BeginInvoke(new Action(()=>{Click(confirmPicker,"Date"+tentativeDay.ToString("yyyyMMdd"));Click(confirmPicker,"ConfirmDates");}),System.Windows.Threading.DispatcherPriority.ContextIdle);bool? confirmed=confirmPicker.ShowDialog();Check(confirmed==true&&confirmPicker.Selection.SetEquals([specifiedPickerDay,tentativeDay])&&originalPickerDates.SequenceEqual([specifiedPickerDay]),"Confirm returns the temporary selection for the caller to commit");
            window.Navigate(false);Set("_date",new DateTime(2026,8,1));typeof(PlannerWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(window,null);Snapshot(window,"15-fixed-six-week-month");Check(body.ScrollableWidth==0&&body.ScrollableHeight==0,"fixed-size six week calendar fits");
            SettingsWindow settings=new(new(),new(),new(),new(),new(),false,null,service.Book.Preferences);settings.NavigateNotifications();settings.Show();await Task.Delay(200);settings.NotificationPage.ScrollToEnd();settings.UpdateLayout();Snapshot(settings,"13-reminder-settings");Check(settings.AlarmAnimationCheckBox.IsVisible&&settings.AlarmSoundCheckBox.IsVisible,"alarm settings integrated below notifications");settings.Close();
            await service.ChangeAsync(b=>{b.Items.Clear();b.Occurrences.Clear();b.Preferences=new(){Sound=false,Animation=true};var i=new ReminderItem{Title="来啦闹钟验证",Start=DateTime.Now,CheckedThrough=DateTime.Now.AddSeconds(-1)};b.Items.Add(i);ReminderEngine.Advance(b,DateTime.Now);});
            bool originalTopmost=Topmost;RefreshReminderCardCore(true);await Task.Delay(180);
            Check(Topmost&&_plannerAlarmTopmost!=null,"alarm temporarily forces pet topmost");
            Check(_plannerAlarmReaction!=null&&_stateMachine.ActiveReactionToken==_plannerAlarmReaction,"original coming animation owns alarm reaction");
            Snapshot(this,"16-original-alarm-animation");
            await service.ChangeAsync(b=>{var o=b.Occurrences.Single();o.RoundStartedAt=DateTime.Now.AddSeconds(-223);ReminderEngine.Advance(b,DateTime.Now);});RefreshReminderCardCore(true);
            Check(service.Book.Occurrences.Single().Phase==ReminderPhase.DueSnoozed,"song timeout enters ten minute retry");
            Check(_plannerAlarmReaction==null&&_plannerAlarmTopmost==null&&Topmost==originalTopmost,"timeout restores prior topmost and animation");
            Check(!ReminderAudio.IsPlaying,"timeout stops reminder audio");
            await service.ChangeAsync(b=>{var o=b.Occurrences.Single();o.SnoozeAt=DateTime.Now;ReminderEngine.Advance(b,DateTime.Now);});RefreshReminderCardCore(true);
            Check(_plannerAlarmReaction!=null&&Topmost,"retry resumes original animation and topmost");
            Click(_reminderCard!,"AcknowledgeReminder");await Task.Delay(200);RefreshReminderCardCore(true);
            Check(!service.Book.Items.Single().Enabled&&service.Book.Occurrences.All(o=>o.RuleId!=service.Book.Items.Single().Id)&&_plannerAlarmReaction==null&&Topmost==originalTopmost&&!ReminderAudio.IsPlaying,"closing a final manual alarm disables but retains its rule, clears the finished occurrence, and releases presentation");
            Check(File.Exists(ReminderAudio.SongPath),"user supplied MP3 packaged locally");
            MediaPlayer media=new(){Volume=0};TaskCompletionSource<bool> opened=new();media.MediaOpened+=(_,_)=>opened.TrySetResult(true);media.MediaFailed+=(_,_)=>opened.TrySetResult(false);media.Open(new Uri(ReminderAudio.SongPath));await Task.WhenAny(opened.Task,Task.Delay(5000));
            Check(media.NaturalDuration.HasTimeSpan&&media.NaturalDuration.TimeSpan.TotalSeconds>220&&media.NaturalDuration.TimeSpan.TotalSeconds<225,"song duration matches three minutes forty two seconds");media.Close();
            await service.ChangeAsync(b=>{b.Items.Clear();b.Occurrences.Clear();b.Preferences=new(){Sound=false,Animation=false};var i=new ReminderItem{Calendar=true,Title="项目讨论",Notes="准备演示资料，确认下一阶段安排。",Start=DateTime.Now.AddMinutes(30),Repeat=ReminderRepeat.Weekly,Weekdays=[DateTime.Today.DayOfWeek],CheckedThrough=DateTime.Now};i.CheckedThrough=i.Start;b.Items.Add(i);b.Occurrences.Add(new(){RuleId=i.Id,At=i.Start,Phase=ReminderPhase.Early});});
            RefreshReminderCardCore(true);await Task.Delay(220);Snapshot(_reminderCard!,"17-early-single");Click(_reminderCard!,"SnoozeReminder");await Task.Delay(200);RefreshReminderCardCore(true);
            Check(service.Book.Occurrences.Single().Phase==ReminderPhase.EarlySnoozed&&!_reminderCard!.IsVisible,"snoozing early reminder creates no quick card");
            await service.ChangeAsync(b=>{var o=b.Occurrences.Single();o.SnoozeAt=DateTime.Now;ReminderEngine.Advance(b,DateTime.Now);});RefreshReminderCardCore(true);Click(_reminderCard!,"AcknowledgeReminder");await Task.Delay(200);RefreshReminderCardCore(true);Snapshot(_reminderCard!,"18-quick-single");
            Click(_reminderCard!,"ToggleQuickReminder");await Task.Delay(230);Snapshot(_reminderCard!,"19-quick-single-expanded");CaptureAttachment();
            var keptItem=service.Book.Items.Single();DateTime occurrenceDate=keptItem.Start.AddDays(7);window.OpenItem(keptItem.Id,occurrenceDate);
            Check((DateTime)typeof(PlannerWindow).GetField("_date",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)! ==occurrenceDate.Date&&(DateTime?)typeof(PlannerWindow).GetField("_occurrenceDate",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)==occurrenceDate,"details target the occurrence date and original item");
            Click(_reminderCard!,"CancelOccurrence");await Task.Delay(200);RefreshReminderCardCore(true);
            Check(!_reminderCard!.IsVisible&&service.Book.Items.Single().Id==keptItem.Id&&service.Book.Items.Single().Enabled,"closing quick card preserves calendar item and enabled repeat rule");
            await service.ChangeAsync(b=>ReminderEngine.Advance(b,keptItem.Start.AddDays(7)));Check(service.Book.Occurrences.Any(o=>o.At==keptItem.Start.AddDays(7)&&o.Phase==ReminderPhase.Due),"next weekly occurrence still rings after cancelling quick card");
            PetReminderCard constrained=new(this);constrained.Present("空间限制验证",new Border{Height=400},true,true);constrained.LimitHeight(140);constrained.Show();constrained.UpdateLayout();
            var constrainedScroll=Tree(constrained).OfType<ScrollViewer>().Single();Check(constrained.ActualHeight<=140&&constrainedScroll.ScrollableHeight>0,"small available space scrolls content instead of clipping actions");constrained.Close();
            await VerifyReminderLayoutQaAsync(service,Check,(w,name)=>Snapshot(w,name,true));
            await VerifyReminderStartupQaAsync(path, Check, (w, name) => Snapshot(w, name, true));
            await RunPlannerRevisionQa(window,service,path,checks);window.Close();_reminderCard.Close();_reminderCard=null;_reminders=null;File.WriteAllLines(Path.Combine(path,"result.txt"),checks);
        }
        catch(Exception ex){File.WriteAllText(Path.Combine(path,"FAILED.txt"),ex.ToString());}
        finally{System.Windows.Application.Current.Shutdown();}
    }
}
