using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Reflection;
using System.Runtime.InteropServices;
using LuoTianyiPet.Core;
using LuoTianyiPet.Platform.Windows;
using Button=System.Windows.Controls.Button;
using CheckBox=System.Windows.Controls.CheckBox;
using TextBox=System.Windows.Controls.TextBox;
namespace LuoTianyiPet.App;
public partial class MainWindow
{
    [DllImport("user32.dll",EntryPoint="GetForegroundWindow")]private static extern nint PlannerQaForeground();
    private async Task RunPlannerQaAsync()
    {
        string path=Path.Combine(AppContext.BaseDirectory,"PlannerQa",DateTime.UtcNow.Ticks.ToString());Directory.CreateDirectory(path);List<string> checks=[];
        try
        {
            using ReminderService service=new(new LocalAppPaths(Path.Combine(path,"UserData")));await service.LoadAsync();
            DateTime day=DateTime.Today.AddDays(1);
            await service.ChangeAsync(b=>{for(int n=0;n<3;n++)b.Items.Add(new ReminderItem{Calendar=true,Title=new[]{"周会","项目讨论","运动"}[n],Notes=new[]{"核对本周计划","准备演示资料，确认下一阶段安排","跑步5公里"}[n],Start=day.AddHours(9+n*4),Enabled=n<2,ReminderCreated=n<2,EarlyEnabled=false});b.Items.Add(new ReminderItem{Title="起床",Start=day.AddHours(8.5),Repeat=ReminderRepeat.Daily,ReminderCreated=true,EarlyEnabled=false});b.Items.Add(new ReminderItem{Title="喝水休息一下",Relative=true,Start=DateTime.Now.AddMinutes(30),DurationSeconds=1800,ReminderCreated=true,EarlyEnabled=false});});
            PlannerWindow window=new(service,false);window.Show();await Task.Delay(150);
            void Check(bool condition,string name){if(!condition)throw new InvalidOperationException(name);checks.Add("PASS "+name);}
            IEnumerable<DependencyObject> Tree(DependencyObject d){yield return d;for(int n=0;n<VisualTreeHelper.GetChildrenCount(d);n++)foreach(var x in Tree(VisualTreeHelper.GetChild(d,n)))yield return x;}
            FrameworkElement Named(Window w,string name)=>Tree(w).OfType<FrameworkElement>().FirstOrDefault(x=>x.Name==name)??throw new InvalidOperationException($"missing named element: {name}");
            void Click(Window w,string name)=>((Button)Named(w,name)).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));
            void Tick(Window w,string name,bool value){var c=(CheckBox)Named(w,name);c.IsChecked=value;c.RaiseEvent(new RoutedEventArgs(CheckBox.ClickEvent));w.UpdateLayout();}
            void Snapshot(Window w,string name,bool dpi=false){w.UpdateLayout();void Shot(string file,double scale){var bmp=new RenderTargetBitmap((int)Math.Ceiling(w.ActualWidth*scale),(int)Math.Ceiling(w.ActualHeight*scale),96*scale,96*scale,PixelFormats.Pbgra32);bmp.Render(w);PngBitmapEncoder png=new();png.Frames.Add(BitmapFrame.Create(bmp));using var f=File.Create(Path.Combine(path,file+".png"));png.Save(f);}Shot(name,1.0);if(dpi){Shot(name+"-125",1.25);Shot(name+"-150",1.5);}checks.Add("PASS rendered "+name+(dpi?" @100/125/150":""));}
            void Set(string name,object value)=>typeof(PlannerWindow).GetField(name,BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(window,value);
            void CaptureAttachment()
            {
                var card=_reminderCard!;var bounds=new Rect(Left,Top,ActualWidth,ActualHeight);bounds.Union(new Rect(card.Left,card.Top,card.ActualWidth,card.ActualHeight));bounds.Inflate(16,16);
                DrawingVisual visual=new();using(var dc=visual.RenderOpen()){dc.DrawRectangle(new SolidColorBrush(Color.FromRgb(234,245,255)),null,new Rect(0,0,bounds.Width,bounds.Height));dc.DrawRectangle(new VisualBrush(this),null,new Rect(Left-bounds.Left,Top-bounds.Top,ActualWidth,ActualHeight));dc.DrawRectangle(new VisualBrush(card),null,new Rect(card.Left-bounds.Left,card.Top-bounds.Top,card.ActualWidth,card.ActualHeight));}
                var bmp=new RenderTargetBitmap((int)Math.Ceiling(bounds.Width),(int)Math.Ceiling(bounds.Height),96,96,PixelFormats.Pbgra32);bmp.Render(visual);PngBitmapEncoder png=new();png.Frames.Add(BitmapFrame.Create(bmp));using var file=File.Create(Path.Combine(path,"20-pet-attached.png"));png.Save(file);checks.Add("PASS rendered pet and attached card in their actual relative positions");
            }
            var precedenceBook=new ReminderBook{RestWeekdays=[DayOfWeek.Friday]};DateTime precedenceDay=new(2026,9,18);ReminderSchedule.SetRestOverride(precedenceBook,precedenceDay,false,DateTime.Now);Check(!precedenceBook.IsRest(precedenceDay),"A31 date override takes priority over weekly rest");ReminderSchedule.SetRestOverride(precedenceBook,precedenceDay,null,DateTime.Now);Check(precedenceBook.IsRest(precedenceDay),"A31 restore default follows weekly rest");
            void Edit(ReminderItem? i,bool calendar){typeof(PlannerWindow).GetMethod("Edit",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(window,new object?[]{i,calendar});window.UpdateLayout();}
            Set("_date",day);window.Navigate(false);Snapshot(window,"01-month",true);
            var body=(ScrollViewer)typeof(PlannerWindow).GetField("_body",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!;
            Check(((Grid)body.Content).ColumnDefinitions.Count==2,"A02 side panel with undimmed month");
            Check(((TextBlock)Named(window,"EffectiveRestStatus")).Text.Contains("跟随每周规则"),"A32 day details explain the effective weekly source");
            Click(window,"Day"+day.ToString("yyyyMMdd"));window.UpdateLayout();Check(((Grid)body.Content).ColumnDefinitions.Count==1,"A02 same date collapses panel");
            Click(window,"Day"+day.ToString("yyyyMMdd"));window.UpdateLayout();
            DateTime overrideDay=day.AddDays(2);await service.ChangeAsync(b=>b.RestWeekdays=[overrideDay.DayOfWeek]);window.UpdateLayout();Click(window,"SetWorkdays");window.UpdateLayout();Check((bool)typeof(PlannerWindow).GetField("_batch",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!,"A31 enters rest adjustment mode");
            Check(!Tree(window).OfType<Button>().Any(b=>Equals(b.Content,"添加日期")),"A30 rest panel uses the main calendar without a duplicate date picker");
            Check(Tree(window).OfType<Button>().Any(b=>Equals(b.Content,"恢复每周安排"))&&!Tree(window).OfType<Button>().Any(b=>Equals(b.Content,"清除指定设置"))&&!Tree(window).OfType<Button>().Any(b=>Equals(b.Content,"恢复默认")),"A32 rest panel names date reset as restoring the weekly schedule");
            Check(Tree(window).OfType<TextBlock>().Any(t=>t.Text.Contains("浅色=每周规则")&&t.Text.Contains("深色=单独设置")),"A32 rest panel explains badge source by color");
            Check(Tree(window).OfType<Button>().Count(b=>Equals(b.Content,"完成班休"))==1,"A31 rest adjustment has one completion action");
            Check(!((Button)Named(window,"ClearSelectedDates")).IsEnabled&&!((Button)Named(window,"SetSelectedRestDays")).IsEnabled&&!((Button)Named(window,"SetSelectedWorkdays")).IsEnabled&&!((Button)Named(window,"ResetSelectedRestDays")).IsEnabled,"A30 empty rest selection disables batch actions");
            Click(window,"Day"+overrideDay.ToString("yyyyMMdd"));window.UpdateLayout();Check((bool)typeof(PlannerWindow).GetField("_batch",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!,"A31 remains in rest adjustment mode after selecting a date");Click(window,"SetSelectedWorkdays");await Task.Delay(200);Check(service.Book.RestOverrides.ContainsKey(overrideDay.ToString("yyyy-MM-dd"))&&!service.Book.IsRest(overrideDay),"A31 UI applies a date workday override over weekly rest");var explicitDateButton=(Button)Named(window,"Day"+overrideDay.ToString("yyyyMMdd"));var explicitHeading=((StackPanel)explicitDateButton.Content).Children.OfType<DockPanel>().First();var explicitBadge=explicitHeading.Children.OfType<Border>().First();Check(Equals(explicitBadge.Background,PlannerTheme.WorkForeground),"A32 explicit workday uses the stronger badge color");Check((bool)typeof(PlannerWindow).GetField("_batch",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!,"A31 stays in rest adjustment mode after applying a rule");Click(window,"Day"+overrideDay.ToString("yyyyMMdd"));window.UpdateLayout();Click(window,"ResetSelectedRestDays");await Task.Delay(200);Check(!service.Book.RestOverrides.ContainsKey(overrideDay.ToString("yyyy-MM-dd"))&&service.Book.IsRest(overrideDay),"A31 UI clears the date override and follows weekly rest");
            var clearedDateButton=(Button)Named(window,"Day"+overrideDay.ToString("yyyyMMdd"));var clearedHeading=((StackPanel)clearedDateButton.Content).Children.OfType<DockPanel>().First();var clearedBadge=clearedHeading.Children.OfType<Border>().First();Check(Equals(clearedDateButton.ToolTip,"跟随每周规则：休息日"),"A32 cleared date explains its effective weekly status");Check(Equals(clearedBadge.Background,PlannerTheme.RestBackground),"A32 cleared date keeps a light effective rest badge");Check(((TextBlock)typeof(PlannerWindow).GetField("_status",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!).Text.Contains("已恢复每周安排"),"A32 cleared date status explains the weekly fallback");
            var restSelection=(HashSet<DateTime>)typeof(PlannerWindow).GetField("_selected",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!;
            Click(window,"Day"+day.ToString("yyyyMMdd"));window.UpdateLayout();Check(restSelection.Count==1&&restSelection.Contains(day),"A30 single click selects one date");Click(window,"Day"+day.ToString("yyyyMMdd"));window.UpdateLayout();Check(restSelection.Count==0,"A30 single click toggles one date off");
            var dragStartButton=(Button)Named(window,"Day"+day.ToString("yyyyMMdd"));var dragEndButton=(Button)Named(window,"Day"+day.AddDays(3).ToString("yyyyMMdd"));var cellPanel=(DockPanel)VisualTreeHelper.GetParent(dragStartButton)!;var dayBorder=(Border)VisualTreeHelper.GetParent(cellPanel)!;var calendarGrid=(Grid)VisualTreeHelper.GetParent(dayBorder)!;
            Point dragFrom=dragStartButton.TransformToAncestor(calendarGrid).Transform(new Point(dragStartButton.ActualWidth/2,dragStartButton.ActualHeight/2));Point dragTo=dragEndButton.TransformToAncestor(calendarGrid).Transform(new Point(dragEndButton.ActualWidth/2,dragEndButton.ActualHeight/2));
            Rect startBounds=dayBorder.TransformToAncestor(calendarGrid).TransformBounds(new Rect(0,0,dayBorder.ActualWidth,dayBorder.ActualHeight));object[] boundaryArgs={calendarGrid,new Point(startBounds.Right,startBounds.Top+startBounds.Height/2),default(DateTime)};bool boundaryHit=(bool)typeof(PlannerWindow).GetMethod("TryGetCalendarDate",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(window,boundaryArgs)!;Check(boundaryHit,"A31 calendar boundary resolves to a nearby date");
            var calendarDragLastDayField=typeof(PlannerWindow).GetField("_calendarDragLastDay",BindingFlags.NonPublic|BindingFlags.Instance)!;typeof(PlannerWindow).GetField("_calendarDragStartDay",BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(window,day);calendarDragLastDayField.SetValue(window,null);typeof(PlannerWindow).GetMethod("AddCalendarDragPath",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(window,new object[]{calendarGrid,dragFrom,dragTo});
            Check(restSelection.Count==4&&Enumerable.Range(0,4).All(n=>restSelection.Contains(day.AddDays(n))),"A30 drag selection includes every date along the path");
            Point reverseFrom=dragTo,reverseTo=dragFrom;typeof(PlannerWindow).GetField("_calendarDragStartDay",BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(window,day.AddDays(3));calendarDragLastDayField.SetValue(window,null);typeof(PlannerWindow).GetMethod("AddCalendarDragPath",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(window,new object[]{calendarGrid,reverseFrom,reverseTo});
            Check(restSelection.Count==0,"A30 reverse drag over the same path cancels every date again");restSelection.Clear();restSelection.Add(day.AddDays(1));restSelection.Add(day.AddDays(3));calendarDragLastDayField.SetValue(window,null);typeof(PlannerWindow).GetField("_calendarDragStartDay",BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(window,day);typeof(PlannerWindow).GetMethod("AddCalendarDragPath",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(window,new object[]{calendarGrid,dragFrom,dragTo});
            Check(restSelection.Count==2&&restSelection.Contains(day)&&restSelection.Contains(day.AddDays(2))&&!restSelection.Contains(day.AddDays(1))&&!restSelection.Contains(day.AddDays(3)),"A30 one drag toggles mixed selected and unselected dates");Snapshot(window,"02-workdays-mixed");await service.ChangeAsync(b=>b.RestWeekdays=[DayOfWeek.Saturday,DayOfWeek.Sunday]);restSelection.Clear();typeof(PlannerWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(window,null);window.UpdateLayout();
            restSelection.Add(day);for(int n=1;n<22;n++)restSelection.Add(day.AddDays(n));typeof(PlannerWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(window,null);window.UpdateLayout();Snapshot(window,"02-workdays-selected",true);
            Check(((Button)Named(window,"ClearSelectedDates")).IsEnabled&&((Button)Named(window,"SetSelectedRestDays")).IsEnabled,"A30 selected rest dates enable clear and batch actions");
            Click(window,"SetSelectedWorkdays");await Task.Delay(200);window.UpdateLayout();
            Check(restSelection.Count==0&&Tree(window).OfType<FrameworkElement>().Any(e=>e.Name=="SetWorkdays")&&Tree(window).OfType<FrameworkElement>().Any(e=>e.Name=="ClearSelectedDates"),"A30 applying a rest rule clears selection and stays in adjust mode");
            Click(window,"Day"+day.ToString("yyyyMMdd"));window.UpdateLayout();Check(restSelection.Count==1,"A30 adjust mode still selects dates after applying a rule");Click(window,"ClearSelectedDates");window.UpdateLayout();Check(restSelection.Count==0,"A30 clear selection removes all selected dates");
            Snapshot(window,"02-workdays",true);Click(window,"SetWorkdays");
            await service.ChangeAsync(b=>b.WeekView=true);Snapshot(window,"03-week",true);await service.ChangeAsync(b=>b.WeekView=false);
            Edit(null,true);Snapshot(window,"04-new-event",true);Check(((CheckBox)Named(window,"CreateAlarm")).IsChecked==false,"A06 new calendar reminder disabled");
            Check(!Tree(window).OfType<FrameworkElement>().Any(e=>e.Name=="EarlyReminder"),"A06 early row absent while disabled");
            var dateControl=(DatePicker)Named(window,"ReminderDate");dateControl.ApplyTemplate();
            ((Button)dateControl.Template.FindName("PART_Button",dateControl)).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await Task.Delay(100);
            var datePopup=(System.Windows.Controls.Primitives.Popup)dateControl.Template.FindName("PART_Popup",dateControl);
            Check(dateControl.IsDropDownOpen&&datePopup.IsOpen&&datePopup.Child!=null,"styled date picker opens a real calendar");dateControl.IsDropDownOpen=false;
            Tick(window,"CreateAlarm",true);Check(((CheckBox)Named(window,"EarlyReminder")).IsChecked==false,"A07 early starts disabled");Tick(window,"EarlyReminder",true);Check(((TextBox)Named(window,"EarlyMinutes")).Text=="30","A07 thirty minute initial value");
            Tick(window,"NoTime",true);Check(((CheckBox)Named(window,"CreateAlarm")).IsChecked==false&&!((CheckBox)Named(window,"CreateAlarm")).IsEnabled,"A29 unspecified time disables reminder");
            ((TextBox)Named(window,"ReminderTitle")).Text="不指定时间事项";Click(window,"SaveReminder");await Task.Delay(250);Check(service.Book.Items.Last().HasTime==false&&!service.Book.Items.Last().Enabled,"A29 unspecified time persists without midnight alarm");
            var eventItem=service.Book.Items.First();Edit(eventItem,true);Snapshot(window,"05-edit-event",true);Check(((TextBox)Named(window,"ReminderNotes")).AcceptsReturn==true,"A09 multi-line note");
            Tick(window,"EarlyReminder",true);((TextBox)Named(window,"EarlyMinutes")).Text="45";Click(window,"SaveReminder");await Task.Delay(250);Check(service.Book.Items.First(i=>i.Id==eventItem.Id).EarlyMinutes==45,"A10 early duration persists");
            window.Navigate(true);Snapshot(window,"06-alarms",true);Edit(null,false);Snapshot(window,"07-new-alarm",true);
            var countdownButton=Tree(window).OfType<Button>().First(b=>Equals(b.Content,"⌛ 倒计时"));countdownButton.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));window.UpdateLayout();Snapshot(window,"08-new-countdown",true);
            void Digits(string h,string m,string s){((TextBox)Named(window,"CountdownHours")).Text=h;((TextBox)Named(window,"CountdownMinutes")).Text=m;((TextBox)Named(window,"CountdownSeconds")).Text=s;}
            foreach(var preset in new[]{("5分钟",300),("15分钟",900),("30分钟",1800),("1小时",3600)}){Tree(window).OfType<Button>().First(b=>Equals(b.Content,preset.Item1)).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));int h=int.Parse(((TextBox)Named(window,"CountdownHours")).Text),m=int.Parse(((TextBox)Named(window,"CountdownMinutes")).Text),sec=int.Parse(((TextBox)Named(window,"CountdownSeconds")).Text);Check(h*3600+m*60+sec==preset.Item2,"A16 preset "+preset.Item1);}
            foreach(string part in new[]{"CountdownHours","CountdownMinutes","CountdownSeconds"}){var input=(TextBox)Named(window,part);input.Text="01";input.RaiseEvent(new System.Windows.Input.MouseWheelEventArgs(System.Windows.Input.Mouse.PrimaryDevice,0,120){RoutedEvent=System.Windows.Input.Mouse.PreviewMouseWheelEvent});Check(input.Text=="02","A16 wheel "+part);}
            int count=service.Book.Items.Count;Digits("24","00","01");Click(window,"SaveReminder");await Task.Delay(100);Check(service.Book.Items.Count==count,"A17 rejects 24:00:01");Digits("0","0","0");Click(window,"SaveReminder");await Task.Delay(100);Check(service.Book.Items.Count==count,"A17 rejects zero");Digits("24","0","0");Click(window,"SaveReminder");await Task.Delay(250);Check(service.Book.Items.Count==count+1&&service.Book.Items.Last().DurationSeconds==86400,"A17 accepts 24 hours with optional empty name");
            var timer=service.Book.Items.Last();await service.ChangeAsync(b=>ReminderEngine.Pause(b,timer.Id,DateTime.Now));var frozen=service.Book.Items.Last().PausedSeconds;await Task.Delay(100);Check(frozen==service.Book.Items.Last().PausedSeconds,"A18 pause freezes remaining");await service.ChangeAsync(b=>ReminderEngine.Resume(b,timer.Id,DateTime.Now));Check(service.Book.Items.Last().PausedSeconds==null,"A18 resume");
            DateTime at=DateTime.Now.AddMinutes(20);await service.ChangeAsync(b=>{b.Items.Clear();b.Occurrences.Clear();for(int n=0;n<2;n++){var i=new ReminderItem{Calendar=true,Title="测试事项"+n,Notes="准备演示资料",Start=at.AddMinutes(n),ReminderCreated=true,EarlyEnabled=true,CheckedThrough=DateTime.Now};i.CheckedThrough=i.Start;b.Items.Add(i);b.Occurrences.Add(new(){RuleId=i.Id,At=i.Start,Phase=ReminderPhase.Early});}});
            _reminders=service;var foreground=PlannerQaForeground();RefreshReminderCardCore(true);Check(PlannerQaForeground()==foreground,"reminder does not steal focus");Snapshot(_reminderCard!,"09-early-reminder");
            Click(_reminderCard!,"AcknowledgeReminder");await Task.Delay(200);RefreshReminderCardCore(true);Check(service.Book.Occurrences.Count(o=>o.Phase==ReminderPhase.AcknowledgedEarly)==1,"A19 acknowledge one early retains due");
            Click(_reminderCard!,"AcknowledgeReminder");await Task.Delay(200);RefreshReminderCardCore(true);Snapshot(_reminderCard!,"10-capsule");Check(service.Book.Occurrences.All(o=>o.Phase==ReminderPhase.AcknowledgedEarly),"A22 both instances combined");
            var sameCard=_reminderCard!;var sameSurface=sameCard.Surface;var sameHeader=sameCard.Header;
            Check(sameCard.ActualHeight<=80&&!sameCard.ShowInTaskbar&&sameCard.Owner==this,"quick card is compact owned pet surface without taskbar icon");
            var workArea=GetQuickActionsWorkArea();Left=workArea.Left+workArea.Width/2-Width/2;Top=workArea.Top+30;RefreshReminderCardCore(true);await Task.Delay(100);
            double baseTop=sameCard.Top,baseLeft=sameCard.Left;
            Click(_reminderCard!,"ToggleQuickReminder");await Task.Delay(230);Snapshot(_reminderCard!,"11-capsule-expanded");
            Check(ReferenceEquals(sameCard,_reminderCard)&&ReferenceEquals(sameSurface,_reminderCard!.Surface)&&ReferenceEquals(sameHeader,_reminderCard.Header),"expansion retains same host border and summary header");
            Check(sameCard.ActualHeight>100&&Math.Abs(sameCard.Top-baseTop)<1,"expansion grows downward with fixed top anchor");
            Click(sameCard,"ToggleQuickReminder");await Task.Delay(230);
            Check(sameCard.ActualHeight<=80&&service.Book.Occurrences.All(o=>o.Phase==ReminderPhase.AcknowledgedEarly),"collapse does not cancel or acknowledge the occurrence");
            _isWindowDragging=true;Left+=35;Top+=15;RefreshReminderCardCore(true);await Task.Delay(100);
            Check(sameCard.IsVisible&&Math.Abs(sameCard.Left-baseLeft-35)<2&&Math.Abs(sameCard.Top-baseTop-15)<2,"quick card follows pet during drag");_isWindowDragging=false;
            Click(sameCard,"ToggleQuickReminder");await Task.Delay(230);
            Click(_reminderCard!,"CancelOccurrence");await Task.Delay(200);Check(service.Book.Occurrences.Count(o=>o.Phase==ReminderPhase.Cancelled)==1,"A21 cancels only selected instance");
            await service.ChangeAsync(b=>ReminderEngine.Advance(b,at.AddMinutes(2)));RefreshReminderCardCore(true);Snapshot(_reminderCard!,"12-due-reminder");Check(!Tree(_reminderCard!).OfType<Button>().Any(b=>b.Name=="CancelOccurrence"),"A24 due only acknowledge and snooze");
            RefreshReminderCardCore(false);Check(!_reminderCard!.IsVisible,"safety hides reminder without dropping data");
            Check(!PlannerPresentationSafe(new(false,null,false))&&!PlannerPresentationSafe(new(true,"YuanShen",false))&&!PlannerPresentationSafe(new(true,"app",true)),"unknown foreground game fullscreen suppress reminders");
            var stored=await new ReminderStore(new LocalAppPaths(Path.Combine(path,"UserData"))).LoadAsync();Check(stored.Occurrences.Any(o=>o.Phase==ReminderPhase.Cancelled),"A27 cancellation survives reload");
            using(var verify=new ReminderService(new LocalAppPaths(Path.Combine(path,"UserData")))){await verify.LoadAsync();Check(verify.Book.Occurrences.Any(o=>o.Phase==ReminderPhase.Cancelled),"A27 service reload preserves cancellation");}
            // Scope actions operate on the original group ID, never on copied date records.
            await service.ChangeAsync(b=>{b.Items.Clear();b.Occurrences.Clear();b.Items.Add(new ReminderItem{Calendar=true,Title="多日期事项",Start=day.AddHours(14),Dates=[day,day.AddDays(7)],Repeat=ReminderRepeat.Dates,ReminderCreated=true,EarlyEnabled=false});});
            window.Navigate(false);Set("_occurrenceDate",day);Edit(service.Book.Items.Single(),true);Click(window,"DeleteOccurrence");window.UpdateLayout();Click(window,"ConfirmGroupDelete");await Task.Delay(200);Check(service.Book.Items.Single().Dates.Count==1,"scope delete keeps other date");
            Set("_manage",true);typeof(PlannerWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(window,null);
            var chosen=(HashSet<Guid>)typeof(PlannerWindow).GetField("_selectedGroups",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)!;chosen.Add(service.Book.Items.Single().Id);typeof(PlannerWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(window,null);Click(window,"DeleteSelectedGroups");window.UpdateLayout();Click(window,"ConfirmGroupDelete");await Task.Delay(200);Check(service.Book.Items.Count==0,"bulk group deletion persists");
            DateSelectionWindow picker=new([day],day){Owner=window};picker.Show();picker.UpdateLayout();Click(picker,"Date"+day.AddDays(1).ToString("yyyyMMdd"));Check(picker.Selection.Count==2,"A13 direct date multiselect");
            picker.Selection.Clear();typeof(DateSelectionWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(picker,null);picker.UpdateLayout();var pickerGrid=Tree(picker).OfType<Grid>().First(g=>g.Children.OfType<Button>().Any(b=>b.Name.StartsWith("Date",StringComparison.Ordinal)));var dragStart=(Button)Named(picker,"Date"+day.AddDays(1).ToString("yyyyMMdd"));var dragEnd=(Button)Named(picker,"Date"+day.AddDays(4).ToString("yyyyMMdd"));Point dateDragFrom=dragStart.TransformToAncestor(pickerGrid).Transform(new Point(dragStart.ActualWidth/2,dragStart.ActualHeight/2));Point dateDragTo=dragEnd.TransformToAncestor(pickerGrid).Transform(new Point(dragEnd.ActualWidth/2,dragEnd.ActualHeight/2));
            typeof(DateSelectionWindow).GetField("_dragLastDay",BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(picker,null);typeof(DateSelectionWindow).GetMethod("ApplyDragPath",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(picker,new object[]{pickerGrid,dateDragFrom,dateDragTo});Check(picker.Selection.Count==4&&Enumerable.Range(1,4).All(n=>picker.Selection.Contains(day.AddDays(n))),"A13 drag selects every date along the path");typeof(DateSelectionWindow).GetField("_dragLastDay",BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(picker,null);typeof(DateSelectionWindow).GetMethod("ApplyDragPath",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(picker,new object[]{pickerGrid,dateDragTo,dateDragFrom});Check(picker.Selection.Count==0,"A13 reverse drag cancels every date again");picker.Selection.Clear();picker.Selection.Add(day.AddDays(2));picker.Selection.Add(day.AddDays(4));typeof(DateSelectionWindow).GetMethod("Render",BindingFlags.NonPublic|BindingFlags.Instance,null,Type.EmptyTypes,null)!.Invoke(picker,null);picker.UpdateLayout();pickerGrid=Tree(picker).OfType<Grid>().First(g=>g.Children.OfType<Button>().Any(b=>b.Name.StartsWith("Date",StringComparison.Ordinal)));dragStart=(Button)Named(picker,"Date"+day.AddDays(1).ToString("yyyyMMdd"));dragEnd=(Button)Named(picker,"Date"+day.AddDays(4).ToString("yyyyMMdd"));dateDragFrom=dragStart.TransformToAncestor(pickerGrid).Transform(new Point(dragStart.ActualWidth/2,dragStart.ActualHeight/2));dateDragTo=dragEnd.TransformToAncestor(pickerGrid).Transform(new Point(dragEnd.ActualWidth/2,dragEnd.ActualHeight/2));typeof(DateSelectionWindow).GetField("_dragLastDay",BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(picker,null);typeof(DateSelectionWindow).GetMethod("ApplyDragPath",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(picker,new object[]{pickerGrid,dateDragFrom,dateDragTo});Check(picker.Selection.Count==2&&picker.Selection.Contains(day.AddDays(1))&&picker.Selection.Contains(day.AddDays(3))&&!picker.Selection.Contains(day.AddDays(2))&&!picker.Selection.Contains(day.AddDays(4)),"A13 drag toggles mixed selected and unselected dates");Snapshot(picker,"14-date-picker");picker.Close();
            window.Navigate(false);window.Width=900;Set("_date",new DateTime(2026,8,1));Snapshot(window,"15-small-six-week-month");Check(body.ScrollableWidth==0&&body.ScrollableHeight==0,"small six week calendar fits");
            SettingsWindow settings=new(new(),new(),new(),new(),new(),false,null,service.Book.Preferences);settings.NavigateNotifications();settings.Show();await Task.Delay(200);settings.NotificationPage.ScrollToEnd();settings.UpdateLayout();Snapshot(settings,"13-reminder-settings");Check(settings.AlarmAnimationCheckBox.IsVisible&&settings.AlarmSoundCheckBox.IsVisible,"alarm settings integrated below notifications");settings.Close();
            await service.ChangeAsync(b=>{b.Items.Clear();b.Occurrences.Clear();b.Preferences=new(){Sound=false,Animation=true};var i=new ReminderItem{Title="来啦闹钟验证",Start=DateTime.Now,CheckedThrough=DateTime.Now.AddSeconds(-1)};b.Items.Add(i);ReminderEngine.Advance(b,DateTime.Now);});
            bool originalTopmost=Topmost;RefreshReminderCardCore(true);await Task.Delay(180);
            Check(Topmost&&_plannerAlarmTopmost!=null,"alarm temporarily forces pet topmost");
            Check(_plannerAlarmReaction!=null&&_stateMachine.ActiveReactionToken==_plannerAlarmReaction,"original coming animation owns alarm reaction");
            Snapshot(this,"16-original-alarm-animation");
            await service.ChangeAsync(b=>{var o=b.Occurrences.Single();o.RoundStartedAt=DateTime.Now.AddSeconds(-223);ReminderEngine.Advance(b,DateTime.Now);});RefreshReminderCardCore(true);
            Check(service.Book.Occurrences.Single().Phase==ReminderPhase.DueSnoozed,"song timeout enters ten minute retry");
            Check(_plannerAlarmReaction==null&&_plannerAlarmTopmost==null&&Topmost==originalTopmost,"timeout restores prior topmost and animation");
            Check(!ReminderAudio.IsPlaying,"timeout stops reminder audio");
            await service.ChangeAsync(b=>{var o=b.Occurrences.Single();o.SnoozeAt=DateTime.Now;ReminderEngine.Advance(b,DateTime.Now);});RefreshReminderCardCore(true);
            Check(_plannerAlarmReaction!=null&&Topmost,"retry resumes original animation and topmost");
            Click(_reminderCard!,"AcknowledgeReminder");await Task.Delay(200);RefreshReminderCardCore(true);
            Check(service.Book.Occurrences.Single().Phase==ReminderPhase.Done&&_plannerAlarmReaction==null&&Topmost==originalTopmost&&!ReminderAudio.IsPlaying,"closing due reminder immediately releases presentation and future retries");
            Check(File.Exists(ReminderAudio.SongPath),"user supplied MP3 packaged locally");
            MediaPlayer media=new(){Volume=0};TaskCompletionSource<bool> opened=new();media.MediaOpened+=(_,_)=>opened.TrySetResult(true);media.MediaFailed+=(_,_)=>opened.TrySetResult(false);media.Open(new Uri(ReminderAudio.SongPath));await Task.WhenAny(opened.Task,Task.Delay(5000));
            Check(media.NaturalDuration.HasTimeSpan&&media.NaturalDuration.TimeSpan.TotalSeconds>220&&media.NaturalDuration.TimeSpan.TotalSeconds<225,"song duration matches three minutes forty two seconds");media.Close();
            await service.ChangeAsync(b=>{b.Items.Clear();b.Occurrences.Clear();b.Preferences=new(){Sound=false,Animation=false};var i=new ReminderItem{Calendar=true,Title="项目讨论",Notes="准备演示资料，确认下一阶段安排。",Start=DateTime.Now.AddMinutes(30),Repeat=ReminderRepeat.Weekly,Weekdays=[DateTime.Today.DayOfWeek],CheckedThrough=DateTime.Now};i.CheckedThrough=i.Start;b.Items.Add(i);b.Occurrences.Add(new(){RuleId=i.Id,At=i.Start,Phase=ReminderPhase.Early});});
            RefreshReminderCardCore(true);await Task.Delay(220);Snapshot(_reminderCard!,"17-early-single");Click(_reminderCard!,"SnoozeReminder");await Task.Delay(200);RefreshReminderCardCore(true);
            Check(service.Book.Occurrences.Single().Phase==ReminderPhase.EarlySnoozed&&!_reminderCard!.IsVisible,"snoozing early reminder creates no quick card");
            await service.ChangeAsync(b=>{var o=b.Occurrences.Single();o.SnoozeAt=DateTime.Now;ReminderEngine.Advance(b,DateTime.Now);});RefreshReminderCardCore(true);Click(_reminderCard!,"AcknowledgeReminder");await Task.Delay(200);RefreshReminderCardCore(true);Snapshot(_reminderCard!,"18-quick-single");
            Click(_reminderCard!,"ToggleQuickReminder");await Task.Delay(230);Snapshot(_reminderCard!,"19-quick-single-expanded");CaptureAttachment();
            var keptItem=service.Book.Items.Single();DateTime occurrenceDate=keptItem.Start.AddDays(7);window.OpenItem(keptItem.Id,occurrenceDate);
            Check((DateTime)typeof(PlannerWindow).GetField("_date",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)! ==occurrenceDate.Date&&(DateTime?)typeof(PlannerWindow).GetField("_occurrenceDate",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(window)==occurrenceDate,"details target the occurrence date and original item");
            Click(_reminderCard!,"CancelOccurrence");await Task.Delay(200);RefreshReminderCardCore(true);
            Check(!_reminderCard!.IsVisible&&service.Book.Items.Single().Id==keptItem.Id&&service.Book.Items.Single().Enabled,"closing quick card preserves calendar item and enabled repeat rule");
            await service.ChangeAsync(b=>ReminderEngine.Advance(b,keptItem.Start.AddDays(7)));Check(service.Book.Occurrences.Any(o=>o.At==keptItem.Start.AddDays(7)&&o.Phase==ReminderPhase.Due),"next weekly occurrence still rings after cancelling quick card");
            PetReminderCard constrained=new(this);constrained.Present("空间限制验证",new Border{Height=400},true,true);constrained.LimitHeight(140);constrained.Show();constrained.UpdateLayout();
            var constrainedScroll=Tree(constrained).OfType<ScrollViewer>().Single();Check(constrained.ActualHeight<=140&&constrainedScroll.ScrollableHeight>0,"small available space scrolls content instead of clipping actions");constrained.Close();
            window.Close();_reminderCard.Close();_reminderCard=null;_reminders=null;File.WriteAllLines(Path.Combine(path,"result.txt"),checks);
        }
        catch(Exception ex){File.WriteAllText(Path.Combine(path,"FAILED.txt"),ex.ToString());}
        finally{System.Windows.Application.Current.Shutdown();}
    }
}
