<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/LuoTianyiPet.Platform.Windows/LuoTianyiPet.Platform.Windows.csproj" />
  </ItemGroup>
</Project>
