<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LuoTianyiPet.Core\LuoTianyiPet.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" Version="3.0.1" Condition="'$(TargetFramework)' != 'net48'" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" Condition="'$(TargetFramework)' == 'net48'" />
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.26100.7705" Condition="'$(TargetFramework)' == 'net48'" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App" Condition="'$(TargetFramework)' != 'net48'" />
    <Reference Include="UIAutomationClient" Condition="'$(TargetFramework)' == 'net48'" />
    <Reference Include="UIAutomationTypes" Condition="'$(TargetFramework)' == 'net48'" />
    <Reference Include="WindowsBase" Condition="'$(TargetFramework)' == 'net48'" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
