using LuoTianyiPet.Platform.Windows;
using LuoTianyiPet.Core;
var readClock=System.Diagnostics.Stopwatch.StartNew();
var reader=WeChatSessionReader.CreateReader();
var snapshot=reader();
Console.WriteLine($"ReadMilliseconds={readClock.ElapsedMilliseconds}");
readClock.Restart();
var repeated=reader();
Console.WriteLine($"ReusedReadMilliseconds={readClock.ElapsedMilliseconds}; Snapshot={repeated is not null}");
Console.WriteLine($"Snapshot={snapshot!=null}; Minimized={snapshot?.Minimized}; Foreground={snapshot?.Foreground}; ParsedRows={snapshot?.Rows.Count}; UnreadRows={snapshot?.Rows.Count(r=>r.HasUnreadMarker)}; MutedRows={snapshot?.Rows.Count(r=>r.Muted)}");
using var source=new WindowsWeChatSessionNotificationSource();
int updates=0, available=0;
source.SnapshotChanged+=(_,_)=>{Interlocked.Increment(ref updates);if(source.HasUnreadConversations is not null)Interlocked.Increment(ref available);};
source.NotificationReceived+=(_,e)=>Console.WriteLine($"Event Provider={e.Provider}; TitleLength={e.Notification.ConversationDisplayName?.Length??0}; PreviewLength={e.Notification.MessagePreview?.Length??0}; HasKey={e.Notification.NotificationKey!=null}");
source.Start();
int seconds=args.Length>0 && int.TryParse(args[0],out int requested) ? Math.Max(1,Math.Min(120,requested)) : 120;
for(int i=0;i<seconds;i++)Thread.Sleep(1000);
source.Stop();Console.WriteLine($"Finished; SnapshotUpdates={updates}; AvailableUpdates={available}");
